namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class DVar_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.TextBox8 = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.TextBox9 = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.TextBox_0 = new global::System.Windows.Forms.TextBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.TextBox_1 = new global::System.Windows.Forms.TextBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextBox_2 = new global::System.Windows.Forms.TextBox();
			this.TextBox_3 = new global::System.Windows.Forms.TextBox();
			this.TextBox_4 = new global::System.Windows.Forms.TextBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.TextBox_5 = new global::System.Windows.Forms.TextBox();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.TextBox_10 = new global::System.Windows.Forms.TextBox();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.TextBox_9 = new global::System.Windows.Forms.TextBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.TextBox_6 = new global::System.Windows.Forms.TextBox();
			this.TextBox_7 = new global::System.Windows.Forms.TextBox();
			this.TextBox_8 = new global::System.Windows.Forms.TextBox();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.SuspendLayout();
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage2);
			this.TabControl1.Controls.Add(this.TabPage3);
			global::System.Windows.Forms.Control tabControl = this.TabControl1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(3, 0);
			tabControl.Location = location;
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl2 = this.TabControl1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(356, 159);
			tabControl2.Size = size;
			this.TabControl1.TabIndex = 0;
			this.TabPage1.Controls.Add(this.Label9);
			this.TabPage1.Controls.Add(this.TextBox8);
			this.TabPage1.Controls.Add(this.Label8);
			this.TabPage1.Controls.Add(this.TextBox7);
			this.TabPage1.Controls.Add(this.Button2);
			this.TabPage1.Controls.Add(this.TextBox6);
			this.TabPage1.Controls.Add(this.Label7);
			this.TabPage1.Controls.Add(this.TextBox5);
			this.TabPage1.Controls.Add(this.TextBox4);
			this.TabPage1.Controls.Add(this.TextBox3);
			this.TabPage1.Controls.Add(this.Label6);
			this.TabPage1.Controls.Add(this.Label5);
			this.TabPage1.Controls.Add(this.Label4);
			this.TabPage1.Controls.Add(this.Label3);
			this.TabPage1.Controls.Add(this.Label2);
			this.TabPage1.Controls.Add(this.TextBox2);
			this.TabPage1.Controls.Add(this.TextBox1);
			this.TabPage1.Controls.Add(this.Label1);
			this.TabPage1.Controls.Add(this.Button1);
			global::System.Windows.Forms.TabPage tabPage = this.TabPage1;
			location = new global::System.Drawing.Point(4, 22);
			tabPage.Location = location;
			this.TabPage1.Name = "TabPage1";
			global::System.Windows.Forms.Control tabPage2 = this.TabPage1;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			tabPage2.Padding = padding;
			global::System.Windows.Forms.Control tabPage3 = this.TabPage1;
			size = new global::System.Drawing.Size(348, 133);
			tabPage3.Size = size;
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "直线阵列";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label9;
			location = new global::System.Drawing.Point(232, 57);
			label.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label2 = this.Label9;
			size = new global::System.Drawing.Size(29, 12);
			label2.Size = size;
			this.Label9.TabIndex = 19;
			this.Label9.Text = "后缀";
			global::System.Windows.Forms.Control textBox = this.TextBox8;
			location = new global::System.Drawing.Point(267, 55);
			textBox.Location = location;
			this.TextBox8.Name = "TextBox8";
			global::System.Windows.Forms.Control textBox2 = this.TextBox8;
			size = new global::System.Drawing.Size(68, 21);
			textBox2.Size = size;
			this.TextBox8.TabIndex = 18;
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label8;
			location = new global::System.Drawing.Point(232, 33);
			label3.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label4 = this.Label8;
			size = new global::System.Drawing.Size(29, 12);
			label4.Size = size;
			this.Label8.TabIndex = 17;
			this.Label8.Text = "前缀";
			global::System.Windows.Forms.Control textBox3 = this.TextBox7;
			location = new global::System.Drawing.Point(267, 31);
			textBox3.Location = location;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox4 = this.TextBox7;
			size = new global::System.Drawing.Size(68, 21);
			textBox4.Size = size;
			this.TextBox7.TabIndex = 16;
			global::System.Windows.Forms.Control button = this.Button2;
			location = new global::System.Drawing.Point(234, 86);
			button.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button2 = this.Button2;
			size = new global::System.Drawing.Size(101, 23);
			button2.Size = size;
			this.Button2.TabIndex = 15;
			this.Button2.Text = "确定";
			this.Button2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox5 = this.TextBox6;
			location = new global::System.Drawing.Point(38, 88);
			textBox5.Location = location;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox6 = this.TextBox6;
			size = new global::System.Drawing.Size(66, 21);
			textBox6.Size = size;
			this.TextBox6.TabIndex = 14;
			this.TextBox6.Text = "300";
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label7;
			location = new global::System.Drawing.Point(114, 58);
			label5.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label6 = this.Label7;
			size = new global::System.Drawing.Size(29, 12);
			label6.Size = size;
			this.Label7.TabIndex = 13;
			this.Label7.Text = "结束";
			global::System.Windows.Forms.Control textBox7 = this.TextBox5;
			location = new global::System.Drawing.Point(149, 85);
			textBox7.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox8 = this.TextBox5;
			size = new global::System.Drawing.Size(82, 21);
			textBox8.Size = size;
			this.TextBox5.TabIndex = 12;
			this.TextBox5.Text = "5";
			global::System.Windows.Forms.Control textBox9 = this.TextBox4;
			location = new global::System.Drawing.Point(149, 58);
			textBox9.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox10 = this.TextBox4;
			size = new global::System.Drawing.Size(82, 21);
			textBox10.Size = size;
			this.TextBox4.TabIndex = 11;
			this.TextBox4.Text = "100";
			global::System.Windows.Forms.Control textBox11 = this.TextBox3;
			location = new global::System.Drawing.Point(149, 30);
			textBox11.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox12 = this.TextBox3;
			size = new global::System.Drawing.Size(82, 21);
			textBox12.Size = size;
			this.TextBox3.TabIndex = 10;
			this.TextBox3.Text = "0";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label6;
			location = new global::System.Drawing.Point(114, 88);
			label7.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label8 = this.Label6;
			size = new global::System.Drawing.Size(29, 12);
			label8.Size = size;
			this.Label6.TabIndex = 9;
			this.Label6.Text = "步距";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label5;
			location = new global::System.Drawing.Point(3, 94);
			label9.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label10 = this.Label5;
			size = new global::System.Drawing.Size(29, 12);
			label10.Size = size;
			this.Label5.TabIndex = 8;
			this.Label5.Text = "字高";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label4;
			location = new global::System.Drawing.Point(114, 33);
			label11.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label12 = this.Label4;
			size = new global::System.Drawing.Size(29, 12);
			label12.Size = size;
			this.Label4.TabIndex = 7;
			this.Label4.Text = "开始";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label3;
			location = new global::System.Drawing.Point(6, 61);
			label13.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label14 = this.Label3;
			size = new global::System.Drawing.Size(11, 12);
			label14.Size = size;
			this.Label3.TabIndex = 6;
			this.Label3.Text = "y";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label2;
			location = new global::System.Drawing.Point(5, 33);
			label15.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label16 = this.Label2;
			size = new global::System.Drawing.Size(11, 12);
			label16.Size = size;
			this.Label2.TabIndex = 5;
			this.Label2.Text = "x";
			global::System.Windows.Forms.Control textBox13 = this.TextBox2;
			location = new global::System.Drawing.Point(22, 58);
			textBox13.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox14 = this.TextBox2;
			size = new global::System.Drawing.Size(82, 21);
			textBox14.Size = size;
			this.TextBox2.TabIndex = 3;
			this.TextBox2.Text = "500";
			global::System.Windows.Forms.Control textBox15 = this.TextBox1;
			location = new global::System.Drawing.Point(22, 31);
			textBox15.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox16 = this.TextBox1;
			size = new global::System.Drawing.Size(82, 21);
			textBox16.Size = size;
			this.TextBox1.TabIndex = 2;
			this.TextBox1.Text = "0";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label1;
			location = new global::System.Drawing.Point(81, 5);
			label17.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label18 = this.Label1;
			size = new global::System.Drawing.Size(0, 12);
			label18.Size = size;
			this.Label1.TabIndex = 1;
			global::System.Windows.Forms.Control button3 = this.Button1;
			location = new global::System.Drawing.Point(0, 0);
			button3.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button4 = this.Button1;
			size = new global::System.Drawing.Size(75, 23);
			button4.Size = size;
			this.Button1.TabIndex = 0;
			this.Button1.Text = "插入点";
			this.Button1.UseVisualStyleBackColor = true;
			this.TabPage2.Controls.Add(this.Label18);
			this.TabPage2.Controls.Add(this.Label10);
			this.TabPage2.Controls.Add(this.TextBox9);
			this.TabPage2.Controls.Add(this.Label11);
			this.TabPage2.Controls.Add(this.TextBox_0);
			this.TabPage2.Controls.Add(this.Button3);
			this.TabPage2.Controls.Add(this.TextBox_1);
			this.TabPage2.Controls.Add(this.Label12);
			this.TabPage2.Controls.Add(this.TextBox_2);
			this.TabPage2.Controls.Add(this.TextBox_3);
			this.TabPage2.Controls.Add(this.TextBox_4);
			this.TabPage2.Controls.Add(this.Label13);
			this.TabPage2.Controls.Add(this.Label14);
			this.TabPage2.Controls.Add(this.Label15);
			this.TabPage2.Controls.Add(this.Label17);
			this.TabPage2.Controls.Add(this.TextBox_5);
			this.TabPage2.Controls.Add(this.Button4);
			global::System.Windows.Forms.TabPage tabPage4 = this.TabPage2;
			location = new global::System.Drawing.Point(4, 22);
			tabPage4.Location = location;
			this.TabPage2.Name = "TabPage2";
			global::System.Windows.Forms.Control tabPage5 = this.TabPage2;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage5.Padding = padding;
			global::System.Windows.Forms.Control tabPage6 = this.TabPage2;
			size = new global::System.Drawing.Size(348, 133);
			tabPage6.Size = size;
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "曲线阵列";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.Label18.AutoSize = true;
			global::System.Windows.Forms.Control label19 = this.Label18;
			location = new global::System.Drawing.Point(83, 6);
			label19.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control label20 = this.Label18;
			size = new global::System.Drawing.Size(0, 12);
			label20.Size = size;
			this.Label18.TabIndex = 38;
			this.Label10.AutoSize = true;
			global::System.Windows.Forms.Control label21 = this.Label10;
			location = new global::System.Drawing.Point(237, 60);
			label21.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label22 = this.Label10;
			size = new global::System.Drawing.Size(29, 12);
			label22.Size = size;
			this.Label10.TabIndex = 37;
			this.Label10.Text = "后缀";
			global::System.Windows.Forms.Control textBox17 = this.TextBox9;
			location = new global::System.Drawing.Point(272, 58);
			textBox17.Location = location;
			this.TextBox9.Name = "TextBox9";
			global::System.Windows.Forms.Control textBox18 = this.TextBox9;
			size = new global::System.Drawing.Size(68, 21);
			textBox18.Size = size;
			this.TextBox9.TabIndex = 36;
			this.Label11.AutoSize = true;
			global::System.Windows.Forms.Control label23 = this.Label11;
			location = new global::System.Drawing.Point(237, 36);
			label23.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label24 = this.Label11;
			size = new global::System.Drawing.Size(29, 12);
			label24.Size = size;
			this.Label11.TabIndex = 35;
			this.Label11.Text = "前缀";
			global::System.Windows.Forms.Control control = this.TextBox_0;
			location = new global::System.Drawing.Point(272, 34);
			control.Location = location;
			this.TextBox_0.Name = "TextBox10";
			global::System.Windows.Forms.Control control2 = this.TextBox_0;
			size = new global::System.Drawing.Size(68, 21);
			control2.Size = size;
			this.TextBox_0.TabIndex = 34;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(239, 89);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(101, 23);
			button6.Size = size;
			this.Button3.TabIndex = 33;
			this.Button3.Text = "确定";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control3 = this.TextBox_1;
			location = new global::System.Drawing.Point(43, 91);
			control3.Location = location;
			this.TextBox_1.Name = "TextBox11";
			global::System.Windows.Forms.Control control4 = this.TextBox_1;
			size = new global::System.Drawing.Size(66, 21);
			control4.Size = size;
			this.TextBox_1.TabIndex = 32;
			this.TextBox_1.Text = "300";
			this.Label12.AutoSize = true;
			global::System.Windows.Forms.Control label25 = this.Label12;
			location = new global::System.Drawing.Point(119, 61);
			label25.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label26 = this.Label12;
			size = new global::System.Drawing.Size(29, 12);
			label26.Size = size;
			this.Label12.TabIndex = 31;
			this.Label12.Text = "结束";
			global::System.Windows.Forms.Control control5 = this.TextBox_2;
			location = new global::System.Drawing.Point(154, 88);
			control5.Location = location;
			this.TextBox_2.Name = "TextBox12";
			global::System.Windows.Forms.Control control6 = this.TextBox_2;
			size = new global::System.Drawing.Size(82, 21);
			control6.Size = size;
			this.TextBox_2.TabIndex = 30;
			this.TextBox_2.Text = "5";
			global::System.Windows.Forms.Control control7 = this.TextBox_3;
			location = new global::System.Drawing.Point(154, 61);
			control7.Location = location;
			this.TextBox_3.Name = "TextBox13";
			global::System.Windows.Forms.Control control8 = this.TextBox_3;
			size = new global::System.Drawing.Size(82, 21);
			control8.Size = size;
			this.TextBox_3.TabIndex = 29;
			this.TextBox_3.Text = "360";
			global::System.Windows.Forms.Control control9 = this.TextBox_4;
			location = new global::System.Drawing.Point(154, 33);
			control9.Location = location;
			this.TextBox_4.Name = "TextBox14";
			global::System.Windows.Forms.Control control10 = this.TextBox_4;
			size = new global::System.Drawing.Size(82, 21);
			control10.Size = size;
			this.TextBox_4.TabIndex = 28;
			this.TextBox_4.Text = "0";
			this.Label13.AutoSize = true;
			global::System.Windows.Forms.Control label27 = this.Label13;
			location = new global::System.Drawing.Point(119, 91);
			label27.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label28 = this.Label13;
			size = new global::System.Drawing.Size(29, 12);
			label28.Size = size;
			this.Label13.TabIndex = 27;
			this.Label13.Text = "步距";
			this.Label14.AutoSize = true;
			global::System.Windows.Forms.Control label29 = this.Label14;
			location = new global::System.Drawing.Point(8, 97);
			label29.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label30 = this.Label14;
			size = new global::System.Drawing.Size(29, 12);
			label30.Size = size;
			this.Label14.TabIndex = 26;
			this.Label14.Text = "字高";
			this.Label15.AutoSize = true;
			global::System.Windows.Forms.Control label31 = this.Label15;
			location = new global::System.Drawing.Point(119, 36);
			label31.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label32 = this.Label15;
			size = new global::System.Drawing.Size(29, 12);
			label32.Size = size;
			this.Label15.TabIndex = 25;
			this.Label15.Text = "开始";
			this.Label17.AutoSize = true;
			global::System.Windows.Forms.Control label33 = this.Label17;
			location = new global::System.Drawing.Point(10, 36);
			label33.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control label34 = this.Label17;
			size = new global::System.Drawing.Size(29, 12);
			label34.Size = size;
			this.Label17.TabIndex = 23;
			this.Label17.Text = "半径";
			global::System.Windows.Forms.Control control11 = this.TextBox_5;
			location = new global::System.Drawing.Point(45, 34);
			control11.Location = location;
			this.TextBox_5.Name = "TextBox16";
			global::System.Windows.Forms.Control control12 = this.TextBox_5;
			size = new global::System.Drawing.Size(64, 21);
			control12.Size = size;
			this.TextBox_5.TabIndex = 21;
			this.TextBox_5.Text = "10000";
			global::System.Windows.Forms.Control button7 = this.Button4;
			location = new global::System.Drawing.Point(5, 3);
			button7.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button8 = this.Button4;
			size = new global::System.Drawing.Size(75, 23);
			button8.Size = size;
			this.Button4.TabIndex = 20;
			this.Button4.Text = "圆心";
			this.Button4.UseVisualStyleBackColor = true;
			this.TabPage3.Controls.Add(this.TextBox_10);
			this.TabPage3.Controls.Add(this.Label22);
			this.TabPage3.Controls.Add(this.TextBox_9);
			this.TabPage3.Controls.Add(this.Label21);
			this.TabPage3.Controls.Add(this.Button5);
			this.TabPage3.Controls.Add(this.Label20);
			this.TabPage3.Controls.Add(this.Label19);
			this.TabPage3.Controls.Add(this.Label16);
			this.TabPage3.Controls.Add(this.TextBox_6);
			this.TabPage3.Controls.Add(this.TextBox_7);
			this.TabPage3.Controls.Add(this.TextBox_8);
			global::System.Windows.Forms.TabPage tabPage7 = this.TabPage3;
			location = new global::System.Drawing.Point(4, 22);
			tabPage7.Location = location;
			this.TabPage3.Name = "TabPage3";
			global::System.Windows.Forms.Control tabPage8 = this.TabPage3;
			size = new global::System.Drawing.Size(348, 133);
			tabPage8.Size = size;
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "前后缀";
			this.TabPage3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control13 = this.TextBox_10;
			location = new global::System.Drawing.Point(152, 18);
			control13.Location = location;
			this.TextBox_10.Name = "TextBox20";
			global::System.Windows.Forms.Control control14 = this.TextBox_10;
			size = new global::System.Drawing.Size(69, 21);
			control14.Size = size;
			this.TextBox_10.TabIndex = 11;
			this.TextBox_10.Text = "300";
			this.Label22.AutoSize = true;
			global::System.Windows.Forms.Control label35 = this.Label22;
			location = new global::System.Drawing.Point(117, 21);
			label35.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control label36 = this.Label22;
			size = new global::System.Drawing.Size(29, 12);
			label36.Size = size;
			this.Label22.TabIndex = 10;
			this.Label22.Text = "字高";
			global::System.Windows.Forms.Control control15 = this.TextBox_9;
			location = new global::System.Drawing.Point(42, 18);
			control15.Location = location;
			this.TextBox_9.Name = "TextBox19";
			global::System.Windows.Forms.Control control16 = this.TextBox_9;
			size = new global::System.Drawing.Size(69, 21);
			control16.Size = size;
			this.TextBox_9.TabIndex = 9;
			this.TextBox_9.Text = "10";
			this.Label21.AutoSize = true;
			global::System.Windows.Forms.Control label37 = this.Label21;
			location = new global::System.Drawing.Point(5, 21);
			label37.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control label38 = this.Label21;
			size = new global::System.Drawing.Size(11, 12);
			label38.Size = size;
			this.Label21.TabIndex = 8;
			this.Label21.Text = "N";
			global::System.Windows.Forms.Control button9 = this.Button5;
			location = new global::System.Drawing.Point(132, 92);
			button9.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button10 = this.Button5;
			size = new global::System.Drawing.Size(75, 23);
			button10.Size = size;
			this.Button5.TabIndex = 7;
			this.Button5.Text = "确定";
			this.Button5.UseVisualStyleBackColor = true;
			this.Label20.AutoSize = true;
			global::System.Windows.Forms.Control label39 = this.Label20;
			location = new global::System.Drawing.Point(117, 58);
			label39.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control label40 = this.Label20;
			size = new global::System.Drawing.Size(29, 12);
			label40.Size = size;
			this.Label20.TabIndex = 5;
			this.Label20.Text = "变量";
			this.Label19.AutoSize = true;
			global::System.Windows.Forms.Control label41 = this.Label19;
			location = new global::System.Drawing.Point(227, 58);
			label41.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control label42 = this.Label19;
			size = new global::System.Drawing.Size(29, 12);
			label42.Size = size;
			this.Label19.TabIndex = 4;
			this.Label19.Text = "后缀";
			this.Label16.AutoSize = true;
			global::System.Windows.Forms.Control label43 = this.Label16;
			location = new global::System.Drawing.Point(5, 58);
			label43.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label44 = this.Label16;
			size = new global::System.Drawing.Size(29, 12);
			label44.Size = size;
			this.Label16.TabIndex = 3;
			this.Label16.Text = "前缀";
			global::System.Windows.Forms.Control control17 = this.TextBox_6;
			location = new global::System.Drawing.Point(262, 55);
			control17.Location = location;
			this.TextBox_6.Name = "TextBox18";
			global::System.Windows.Forms.Control control18 = this.TextBox_6;
			size = new global::System.Drawing.Size(69, 21);
			control18.Size = size;
			this.TextBox_6.TabIndex = 2;
			this.TextBox_6.Text = "/N";
			global::System.Windows.Forms.Control control19 = this.TextBox_7;
			location = new global::System.Drawing.Point(152, 55);
			control19.Location = location;
			this.TextBox_7.Name = "TextBox17";
			global::System.Windows.Forms.Control control20 = this.TextBox_7;
			size = new global::System.Drawing.Size(69, 21);
			control20.Size = size;
			this.TextBox_7.TabIndex = 1;
			this.TextBox_7.Text = "1";
			global::System.Windows.Forms.Control control21 = this.TextBox_8;
			location = new global::System.Drawing.Point(42, 55);
			control21.Location = location;
			this.TextBox_8.Name = "TextBox15";
			global::System.Windows.Forms.Control control22 = this.TextBox_8;
			size = new global::System.Drawing.Size(69, 21);
			control22.Size = size;
			this.TextBox_8.TabIndex = 0;
			this.TextBox_8.Text = "结施-";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(361, 161);
			this.ClientSize = size;
			this.Controls.Add(this.TabControl1);
			this.Name = "DVar_Frm";
			this.Text = "动态变量";
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			this.TabPage3.ResumeLayout(false);
			this.TabPage3.PerformLayout();
			this.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
