namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Filter_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.TextBox8 = new global::System.Windows.Forms.TextBox();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.Button14 = new global::System.Windows.Forms.Button();
			this.Button15 = new global::System.Windows.Forms.Button();
			this.Button16 = new global::System.Windows.Forms.Button();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.Button19 = new global::System.Windows.Forms.Button();
			this.Button20 = new global::System.Windows.Forms.Button();
			this.Button21 = new global::System.Windows.Forms.Button();
			this.Button22 = new global::System.Windows.Forms.Button();
			this.Button23 = new global::System.Windows.Forms.Button();
			this.Button24 = new global::System.Windows.Forms.Button();
			this.Button25 = new global::System.Windows.Forms.Button();
			this.SuspendLayout();
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(58, 8);
			textBox.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(133, 21);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 1;
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			location = new global::System.Drawing.Point(58, 33);
			textBox3.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new global::System.Drawing.Size(133, 21);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 3;
			global::System.Windows.Forms.Control textBox5 = this.TextBox4;
			location = new global::System.Drawing.Point(58, 139);
			textBox5.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox6 = this.TextBox4;
			size = new global::System.Drawing.Size(133, 21);
			textBox6.Size = size;
			this.TextBox4.TabIndex = 7;
			global::System.Windows.Forms.Control textBox7 = this.TextBox3;
			location = new global::System.Drawing.Point(58, 58);
			textBox7.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox8 = this.TextBox3;
			size = new global::System.Drawing.Size(133, 21);
			textBox8.Size = size;
			this.TextBox3.TabIndex = 9;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(197, 5);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(26, 20);
			button2.Size = size;
			this.Button1.TabIndex = 10;
			this.Button1.Text = "..";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(197, 31);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(26, 20);
			button4.Size = size;
			this.Button2.TabIndex = 11;
			this.Button2.Text = "..";
			this.Button2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(197, 58);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(26, 20);
			button6.Size = size;
			this.Button3.TabIndex = 12;
			this.Button3.Text = "..";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button7 = this.Button4;
			location = new global::System.Drawing.Point(197, 140);
			button7.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button8 = this.Button4;
			size = new global::System.Drawing.Size(26, 20);
			button8.Size = size;
			this.Button4.TabIndex = 13;
			this.Button4.Text = "..";
			this.Button4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox9 = this.TextBox5;
			location = new global::System.Drawing.Point(58, 85);
			textBox9.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox10 = this.TextBox5;
			size = new global::System.Drawing.Size(133, 21);
			textBox10.Size = size;
			this.TextBox5.TabIndex = 14;
			global::System.Windows.Forms.Control button9 = this.Button5;
			location = new global::System.Drawing.Point(197, 86);
			button9.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button10 = this.Button5;
			size = new global::System.Drawing.Size(26, 20);
			button10.Size = size;
			this.Button5.TabIndex = 15;
			this.Button5.Text = "..";
			this.Button5.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button11 = this.Button6;
			location = new global::System.Drawing.Point(197, 113);
			button11.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button12 = this.Button6;
			size = new global::System.Drawing.Size(26, 20);
			button12.Size = size;
			this.Button6.TabIndex = 18;
			this.Button6.Text = "..";
			this.Button6.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox11 = this.TextBox6;
			location = new global::System.Drawing.Point(58, 112);
			textBox11.Location = location;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox12 = this.TextBox6;
			size = new global::System.Drawing.Size(133, 21);
			textBox12.Size = size;
			this.TextBox6.TabIndex = 17;
			global::System.Windows.Forms.Control button13 = this.Button7;
			location = new global::System.Drawing.Point(197, 167);
			button13.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button14 = this.Button7;
			size = new global::System.Drawing.Size(26, 20);
			button14.Size = size;
			this.Button7.TabIndex = 27;
			this.Button7.Text = "..";
			this.Button7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox13 = this.TextBox7;
			location = new global::System.Drawing.Point(58, 166);
			textBox13.Location = location;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox14 = this.TextBox7;
			size = new global::System.Drawing.Size(133, 21);
			textBox14.Size = size;
			this.TextBox7.TabIndex = 26;
			global::System.Windows.Forms.Control button15 = this.Button8;
			location = new global::System.Drawing.Point(197, 194);
			button15.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button16 = this.Button8;
			size = new global::System.Drawing.Size(26, 20);
			button16.Size = size;
			this.Button8.TabIndex = 31;
			this.Button8.Text = "..";
			this.Button8.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox15 = this.TextBox8;
			location = new global::System.Drawing.Point(58, 193);
			textBox15.Location = location;
			this.TextBox8.Name = "TextBox8";
			global::System.Windows.Forms.Control textBox16 = this.TextBox8;
			size = new global::System.Drawing.Size(133, 21);
			textBox16.Size = size;
			this.TextBox8.TabIndex = 30;
			global::System.Windows.Forms.Control button17 = this.Button9;
			location = new global::System.Drawing.Point(181, 224);
			button17.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button18 = this.Button9;
			size = new global::System.Drawing.Size(80, 24);
			button18.Size = size;
			this.Button9.TabIndex = 33;
			this.Button9.Text = "确定";
			this.Button9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button19 = this.Button10;
			location = new global::System.Drawing.Point(229, 195);
			button19.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button20 = this.Button10;
			size = new global::System.Drawing.Size(32, 20);
			button20.Size = size;
			this.Button10.TabIndex = 41;
			this.Button10.Text = "And";
			this.Button10.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button21 = this.Button11;
			location = new global::System.Drawing.Point(229, 168);
			button21.Location = location;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control button22 = this.Button11;
			size = new global::System.Drawing.Size(32, 20);
			button22.Size = size;
			this.Button11.TabIndex = 40;
			this.Button11.Text = "And";
			this.Button11.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button23 = this.Button12;
			location = new global::System.Drawing.Point(229, 114);
			button23.Location = location;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button24 = this.Button12;
			size = new global::System.Drawing.Size(32, 20);
			button24.Size = size;
			this.Button12.TabIndex = 39;
			this.Button12.Text = "And";
			this.Button12.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button25 = this.Button13;
			location = new global::System.Drawing.Point(229, 87);
			button25.Location = location;
			this.Button13.Name = "Button13";
			global::System.Windows.Forms.Control button26 = this.Button13;
			size = new global::System.Drawing.Size(32, 20);
			button26.Size = size;
			this.Button13.TabIndex = 38;
			this.Button13.Text = "And";
			this.Button13.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button27 = this.Button14;
			location = new global::System.Drawing.Point(229, 141);
			button27.Location = location;
			this.Button14.Name = "Button14";
			global::System.Windows.Forms.Control button28 = this.Button14;
			size = new global::System.Drawing.Size(32, 20);
			button28.Size = size;
			this.Button14.TabIndex = 37;
			this.Button14.Text = "And";
			this.Button14.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button29 = this.Button15;
			location = new global::System.Drawing.Point(229, 59);
			button29.Location = location;
			this.Button15.Name = "Button15";
			global::System.Windows.Forms.Control button30 = this.Button15;
			size = new global::System.Drawing.Size(32, 20);
			button30.Size = size;
			this.Button15.TabIndex = 36;
			this.Button15.Text = "And";
			this.Button15.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button31 = this.Button16;
			location = new global::System.Drawing.Point(229, 32);
			button31.Location = location;
			this.Button16.Name = "Button16";
			global::System.Windows.Forms.Control button32 = this.Button16;
			size = new global::System.Drawing.Size(32, 20);
			button32.Size = size;
			this.Button16.TabIndex = 35;
			this.Button16.Text = "And";
			this.Button16.UseVisualStyleBackColor = true;
			this.Button17.BackColor = global::System.Drawing.SystemColors.Control;
			global::System.Windows.Forms.Control button33 = this.Button17;
			location = new global::System.Drawing.Point(229, 6);
			button33.Location = location;
			this.Button17.Name = "Button17";
			global::System.Windows.Forms.Control button34 = this.Button17;
			size = new global::System.Drawing.Size(32, 20);
			button34.Size = size;
			this.Button17.TabIndex = 34;
			this.Button17.Text = "And";
			this.Button17.UseVisualStyleBackColor = false;
			global::System.Windows.Forms.Control button35 = this.Button18;
			location = new global::System.Drawing.Point(12, 197);
			button35.Location = location;
			this.Button18.Name = "Button18";
			global::System.Windows.Forms.Control button36 = this.Button18;
			size = new global::System.Drawing.Size(40, 20);
			button36.Size = size;
			this.Button18.TabIndex = 49;
			this.Button18.Text = "半径";
			this.Button18.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button37 = this.Button19;
			location = new global::System.Drawing.Point(12, 170);
			button37.Location = location;
			this.Button19.Name = "Button19";
			global::System.Windows.Forms.Control button38 = this.Button19;
			size = new global::System.Drawing.Size(40, 20);
			button38.Size = size;
			this.Button19.TabIndex = 48;
			this.Button19.Text = "长度";
			this.Button19.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button39 = this.Button20;
			location = new global::System.Drawing.Point(12, 116);
			button39.Location = location;
			this.Button20.Name = "Button20";
			global::System.Windows.Forms.Control button40 = this.Button20;
			size = new global::System.Drawing.Size(40, 20);
			button40.Size = size;
			this.Button20.TabIndex = 47;
			this.Button20.Text = "图块";
			this.Button20.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button41 = this.Button21;
			location = new global::System.Drawing.Point(12, 89);
			button41.Location = location;
			this.Button21.Name = "Button21";
			global::System.Windows.Forms.Control button42 = this.Button21;
			size = new global::System.Drawing.Size(40, 20);
			button42.Size = size;
			this.Button21.TabIndex = 46;
			this.Button21.Text = "文字";
			this.Button21.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button43 = this.Button22;
			location = new global::System.Drawing.Point(12, 143);
			button43.Location = location;
			this.Button22.Name = "Button22";
			global::System.Windows.Forms.Control button44 = this.Button22;
			size = new global::System.Drawing.Size(40, 20);
			button44.Size = size;
			this.Button22.TabIndex = 45;
			this.Button22.Text = "角度";
			this.Button22.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button45 = this.Button23;
			location = new global::System.Drawing.Point(12, 61);
			button45.Location = location;
			this.Button23.Name = "Button23";
			global::System.Windows.Forms.Control button46 = this.Button23;
			size = new global::System.Drawing.Size(40, 20);
			button46.Size = size;
			this.Button23.TabIndex = 44;
			this.Button23.Text = "颜色";
			this.Button23.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button47 = this.Button24;
			location = new global::System.Drawing.Point(12, 34);
			button47.Location = location;
			this.Button24.Name = "Button24";
			global::System.Windows.Forms.Control button48 = this.Button24;
			size = new global::System.Drawing.Size(40, 20);
			button48.Size = size;
			this.Button24.TabIndex = 43;
			this.Button24.Text = "图层";
			this.Button24.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button49 = this.Button25;
			location = new global::System.Drawing.Point(12, 8);
			button49.Location = location;
			this.Button25.Name = "Button25";
			global::System.Windows.Forms.Control button50 = this.Button25;
			size = new global::System.Drawing.Size(40, 20);
			button50.Size = size;
			this.Button25.TabIndex = 42;
			this.Button25.Text = "图元";
			this.Button25.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(271, 260);
			this.ClientSize = size;
			this.Controls.Add(this.Button18);
			this.Controls.Add(this.Button19);
			this.Controls.Add(this.Button20);
			this.Controls.Add(this.Button21);
			this.Controls.Add(this.Button22);
			this.Controls.Add(this.Button23);
			this.Controls.Add(this.Button24);
			this.Controls.Add(this.Button25);
			this.Controls.Add(this.Button10);
			this.Controls.Add(this.Button11);
			this.Controls.Add(this.Button12);
			this.Controls.Add(this.Button13);
			this.Controls.Add(this.Button14);
			this.Controls.Add(this.Button15);
			this.Controls.Add(this.Button16);
			this.Controls.Add(this.Button17);
			this.Controls.Add(this.Button9);
			this.Controls.Add(this.Button8);
			this.Controls.Add(this.TextBox8);
			this.Controls.Add(this.Button7);
			this.Controls.Add(this.TextBox7);
			this.Controls.Add(this.Button6);
			this.Controls.Add(this.TextBox6);
			this.Controls.Add(this.Button5);
			this.Controls.Add(this.TextBox5);
			this.Controls.Add(this.Button4);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.TextBox3);
			this.Controls.Add(this.TextBox4);
			this.Controls.Add(this.TextBox2);
			this.Controls.Add(this.TextBox1);
			this.Name = "Filter_Frm";
			this.Text = "过滤器";
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
