namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class LJM_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.icontainer_0 = new global::System.ComponentModel.Container();
			this.TableLayoutPanel1 = new global::System.Windows.Forms.TableLayoutPanel();
			this.OK_Button = new global::System.Windows.Forms.Button();
			this.Cancel_Button = new global::System.Windows.Forms.Button();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.ImageList1 = new global::System.Windows.Forms.ImageList(this.icontainer_0);
			this.TableLayoutPanel1.SuspendLayout();
			this.SuspendLayout();
			this.TableLayoutPanel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.TableLayoutPanel1.ColumnCount = 2;
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.TableLayoutPanel1.Controls.Add(this.OK_Button, 0, 0);
			this.TableLayoutPanel1.Controls.Add(this.Cancel_Button, 1, 0);
			global::System.Windows.Forms.Control tableLayoutPanel = this.TableLayoutPanel1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(10, 167);
			tableLayoutPanel.Location = location;
			this.TableLayoutPanel1.Name = "TableLayoutPanel1";
			this.TableLayoutPanel1.RowCount = 1;
			this.TableLayoutPanel1.RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			global::System.Windows.Forms.Control tableLayoutPanel2 = this.TableLayoutPanel1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(167, 27);
			tableLayoutPanel2.Size = size;
			this.TableLayoutPanel1.TabIndex = 0;
			this.OK_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			global::System.Windows.Forms.Control ok_Button = this.OK_Button;
			location = new global::System.Drawing.Point(8, 3);
			ok_Button.Location = location;
			this.OK_Button.Name = "OK_Button";
			global::System.Windows.Forms.Control ok_Button2 = this.OK_Button;
			size = new global::System.Drawing.Size(67, 21);
			ok_Button2.Size = size;
			this.OK_Button.TabIndex = 0;
			this.OK_Button.Text = "确定";
			this.Cancel_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Cancel_Button.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			global::System.Windows.Forms.Control cancel_Button = this.Cancel_Button;
			location = new global::System.Drawing.Point(91, 3);
			cancel_Button.Location = location;
			this.Cancel_Button.Name = "Cancel_Button";
			global::System.Windows.Forms.Control cancel_Button2 = this.Cancel_Button;
			size = new global::System.Drawing.Size(67, 21);
			cancel_Button2.Size = size;
			this.Cancel_Button.TabIndex = 1;
			this.Cancel_Button.Text = "取消";
			global::System.Windows.Forms.Control textBox = this.TextBox2;
			location = new global::System.Drawing.Point(73, 28);
			textBox.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox2 = this.TextBox2;
			size = new global::System.Drawing.Size(104, 21);
			textBox2.Size = size;
			this.TextBox2.TabIndex = 2;
			this.TextBox2.Text = "4C25/2C20";
			global::System.Windows.Forms.Control textBox3 = this.TextBox3;
			location = new global::System.Drawing.Point(73, 52);
			textBox3.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox4 = this.TextBox3;
			size = new global::System.Drawing.Size(104, 21);
			textBox4.Size = size;
			this.TextBox3.TabIndex = 3;
			this.TextBox3.Text = "2C20/4C25";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(10, 31);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(53, 12);
			label2.Size = size;
			this.Label1.TabIndex = 4;
			this.Label1.Text = "顶部钢筋";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new global::System.Drawing.Point(10, 55);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(53, 12);
			label4.Size = size;
			this.Label2.TabIndex = 5;
			this.Label2.Text = "下部钢筋";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new global::System.Drawing.Point(10, 7);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(53, 12);
			label6.Size = size;
			this.Label3.TabIndex = 7;
			this.Label3.Text = "截面尺寸";
			global::System.Windows.Forms.Control textBox5 = this.TextBox1;
			location = new global::System.Drawing.Point(73, 4);
			textBox5.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox6 = this.TextBox1;
			size = new global::System.Drawing.Size(104, 21);
			textBox6.Size = size;
			this.TextBox1.TabIndex = 6;
			this.TextBox1.Text = "250/500";
			global::System.Windows.Forms.Control textBox7 = this.TextBox7;
			location = new global::System.Drawing.Point(96, 132);
			textBox7.Location = location;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox8 = this.TextBox7;
			size = new global::System.Drawing.Size(81, 21);
			textBox8.Size = size;
			this.TextBox7.TabIndex = 9;
			this.TextBox7.Text = "3.000";
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(10, 132);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(80, 24);
			button2.Size = size;
			this.Button1.TabIndex = 10;
			this.Button1.Text = "顶部标高";
			this.Button1.UseVisualStyleBackColor = true;
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label4;
			location = new global::System.Drawing.Point(10, 103);
			label7.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(53, 12);
			label8.Size = size;
			this.Label4.TabIndex = 12;
			this.Label4.Text = "两侧钢筋";
			global::System.Windows.Forms.Control textBox9 = this.TextBox5;
			location = new global::System.Drawing.Point(73, 100);
			textBox9.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox10 = this.TextBox5;
			size = new global::System.Drawing.Size(104, 21);
			textBox10.Size = size;
			this.TextBox5.TabIndex = 11;
			this.TextBox5.Text = "2C12";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label6;
			location = new global::System.Drawing.Point(34, 79);
			label9.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label10 = this.Label6;
			size = new global::System.Drawing.Size(29, 12);
			label10.Size = size;
			this.Label6.TabIndex = 17;
			this.Label6.Text = "箍筋";
			global::System.Windows.Forms.Control textBox11 = this.TextBox4;
			location = new global::System.Drawing.Point(73, 76);
			textBox11.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox12 = this.TextBox4;
			size = new global::System.Drawing.Size(104, 21);
			textBox12.Size = size;
			this.TextBox4.TabIndex = 16;
			this.TextBox4.Text = "C8@100/200";
			this.ImageList1.ColorDepth = global::System.Windows.Forms.ColorDepth.Depth8Bit;
			global::System.Windows.Forms.ImageList imageList = this.ImageList1;
			size = new global::System.Drawing.Size(16, 16);
			imageList.ImageSize = size;
			this.ImageList1.TransparentColor = global::System.Drawing.Color.Transparent;
			this.AcceptButton = this.OK_Button;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.Cancel_Button;
			size = new global::System.Drawing.Size(184, 206);
			this.ClientSize = size;
			this.Controls.Add(this.Label6);
			this.Controls.Add(this.TextBox4);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.TextBox5);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.TextBox7);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.TextBox1);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.TextBox3);
			this.Controls.Add(this.TextBox2);
			this.Controls.Add(this.TableLayoutPanel1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "LJM_Frm";
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "梁截面";
			this.TableLayoutPanel1.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
