namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcAsv_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.Label5 = new global::System.Windows.Forms.Label();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.TextBox8 = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.ComboBox3 = new global::System.Windows.Forms.ComboBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.ComboBox5 = new global::System.Windows.Forms.ComboBox();
			this.TextBox_0 = new global::System.Windows.Forms.TextBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.TextBox_1 = new global::System.Windows.Forms.TextBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.ComboBox4 = new global::System.Windows.Forms.ComboBox();
			this.TextBox9 = new global::System.Windows.Forms.TextBox();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.ListBox1 = new global::System.Windows.Forms.ListBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.TextBox_2 = new global::System.Windows.Forms.TextBox();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.TextBox_3 = new global::System.Windows.Forms.TextBox();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.SuspendLayout();
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label5;
			global::System.Drawing.Point location = new global::System.Drawing.Point(10, 84);
			label.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label2 = this.Label5;
			global::System.Drawing.Size size = new global::System.Drawing.Size(53, 12);
			label2.Size = size;
			this.Label5.TabIndex = 8;
			this.Label5.Text = "箍筋总长";
			this.TextBox4.Enabled = false;
			global::System.Windows.Forms.Control textBox = this.TextBox4;
			location = new global::System.Drawing.Point(69, 58);
			textBox.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox2 = this.TextBox4;
			size = new global::System.Drawing.Size(70, 21);
			textBox2.Size = size;
			this.TextBox4.TabIndex = 9;
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label6;
			location = new global::System.Drawing.Point(10, 107);
			label3.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label4 = this.Label6;
			size = new global::System.Drawing.Size(59, 12);
			label4.Size = size;
			this.Label6.TabIndex = 10;
			this.Label6.Text = "配箍率(%)";
			this.TextBox5.Enabled = false;
			global::System.Windows.Forms.Control textBox3 = this.TextBox5;
			location = new global::System.Drawing.Point(69, 81);
			textBox3.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox4 = this.TextBox5;
			size = new global::System.Drawing.Size(70, 21);
			textBox4.Size = size;
			this.TextBox5.TabIndex = 11;
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label7;
			location = new global::System.Drawing.Point(10, 61);
			label5.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label6 = this.Label7;
			size = new global::System.Drawing.Size(41, 12);
			label6.Size = size;
			this.Label7.TabIndex = 12;
			this.Label7.Text = "核心区";
			global::System.Windows.Forms.Control textBox5 = this.TextBox6;
			location = new global::System.Drawing.Point(69, 104);
			textBox5.Location = location;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox6 = this.TextBox6;
			size = new global::System.Drawing.Size(70, 21);
			textBox6.Size = size;
			this.TextBox6.TabIndex = 13;
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label8;
			location = new global::System.Drawing.Point(6, 38);
			label7.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label8 = this.Label8;
			size = new global::System.Drawing.Size(41, 12);
			label8.Size = size;
			this.Label8.TabIndex = 14;
			this.Label8.Text = "混凝土";
			this.ComboBox2.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox = this.ComboBox2;
			location = new global::System.Drawing.Point(85, 34);
			comboBox.Location = location;
			this.ComboBox2.Name = "ComboBox2";
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox2;
			size = new global::System.Drawing.Size(65, 20);
			comboBox2.Size = size;
			this.ComboBox2.TabIndex = 2;
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label9;
			location = new global::System.Drawing.Point(6, 107);
			label9.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label10 = this.Label9;
			size = new global::System.Drawing.Size(65, 12);
			label10.Size = size;
			this.Label9.TabIndex = 16;
			this.Label9.Text = "配箍特征值";
			global::System.Windows.Forms.Control textBox7 = this.TextBox7;
			location = new global::System.Drawing.Point(85, 101);
			textBox7.Location = location;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox8 = this.TextBox7;
			size = new global::System.Drawing.Size(65, 21);
			textBox8.Size = size;
			this.TextBox7.TabIndex = 5;
			this.Label10.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label10;
			location = new global::System.Drawing.Point(20, 152);
			label11.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label12 = this.Label10;
			size = new global::System.Drawing.Size(59, 12);
			label12.Size = size;
			this.Label10.TabIndex = 18;
			this.Label10.Text = "配箍率(%)";
			global::System.Windows.Forms.Control textBox9 = this.TextBox8;
			location = new global::System.Drawing.Point(97, 148);
			textBox9.Location = location;
			this.TextBox8.Name = "TextBox8";
			global::System.Windows.Forms.Control textBox10 = this.TextBox8;
			size = new global::System.Drawing.Size(65, 21);
			textBox10.Size = size;
			this.TextBox8.TabIndex = 6;
			this.Label11.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label11;
			location = new global::System.Drawing.Point(6, 61);
			label13.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label14 = this.Label11;
			size = new global::System.Drawing.Size(29, 12);
			label14.Size = size;
			this.Label11.TabIndex = 20;
			this.Label11.Text = "钢筋";
			this.ComboBox3.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox3 = this.ComboBox3;
			location = new global::System.Drawing.Point(85, 56);
			comboBox3.Location = location;
			this.ComboBox3.Name = "ComboBox3";
			global::System.Windows.Forms.Control comboBox4 = this.ComboBox3;
			size = new global::System.Drawing.Size(65, 20);
			comboBox4.Size = size;
			this.ComboBox3.TabIndex = 3;
			this.GroupBox1.Controls.Add(this.Label15);
			this.GroupBox1.Controls.Add(this.Label14);
			this.GroupBox1.Controls.Add(this.Label8);
			this.GroupBox1.Controls.Add(this.Label11);
			this.GroupBox1.Controls.Add(this.Label9);
			this.GroupBox1.Controls.Add(this.ComboBox5);
			this.GroupBox1.Controls.Add(this.ComboBox2);
			this.GroupBox1.Controls.Add(this.ComboBox3);
			this.GroupBox1.Controls.Add(this.TextBox_0);
			this.GroupBox1.Controls.Add(this.TextBox7);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new global::System.Drawing.Point(12, 7);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(156, 133);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 22;
			this.GroupBox1.TabStop = false;
			this.Label15.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label15;
			location = new global::System.Drawing.Point(8, 84);
			label15.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label16 = this.Label15;
			size = new global::System.Drawing.Size(41, 12);
			label16.Size = size;
			this.Label15.TabIndex = 24;
			this.Label15.Text = "轴压比";
			this.Label14.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label14;
			location = new global::System.Drawing.Point(6, 15);
			label17.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label18 = this.Label14;
			size = new global::System.Drawing.Size(29, 12);
			label18.Size = size;
			this.Label14.TabIndex = 22;
			this.Label14.Text = "抗震";
			this.ComboBox5.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox5 = this.ComboBox5;
			location = new global::System.Drawing.Point(41, 13);
			comboBox5.Location = location;
			this.ComboBox5.Name = "ComboBox5";
			global::System.Windows.Forms.Control comboBox6 = this.ComboBox5;
			size = new global::System.Drawing.Size(109, 20);
			comboBox6.Size = size;
			this.ComboBox5.TabIndex = 1;
			global::System.Windows.Forms.Control control = this.TextBox_0;
			location = new global::System.Drawing.Point(85, 78);
			control.Location = location;
			this.TextBox_0.Name = "TextBox10";
			global::System.Windows.Forms.Control control2 = this.TextBox_0;
			size = new global::System.Drawing.Size(65, 21);
			control2.Size = size;
			this.TextBox_0.TabIndex = 4;
			this.GroupBox2.Controls.Add(this.Label16);
			this.GroupBox2.Controls.Add(this.TextBox_1);
			this.GroupBox2.Controls.Add(this.Label12);
			this.GroupBox2.Controls.Add(this.Label1);
			this.GroupBox2.Controls.Add(this.Label13);
			this.GroupBox2.Controls.Add(this.Label4);
			this.GroupBox2.Controls.Add(this.ComboBox4);
			this.GroupBox2.Controls.Add(this.TextBox9);
			this.GroupBox2.Controls.Add(this.ComboBox1);
			this.GroupBox2.Controls.Add(this.TextBox3);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			location = new global::System.Drawing.Point(12, 173);
			groupBox3.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(156, 131);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 29;
			this.GroupBox2.TabStop = false;
			this.Label16.AutoSize = true;
			this.Label16.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label19 = this.Label16;
			location = new global::System.Drawing.Point(6, 40);
			label19.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label20 = this.Label16;
			size = new global::System.Drawing.Size(53, 12);
			label20.Size = size;
			this.Label16.TabIndex = 27;
			this.Label16.Text = "绘图间隙";
			global::System.Windows.Forms.Control control3 = this.TextBox_1;
			location = new global::System.Drawing.Point(85, 37);
			control3.Location = location;
			this.TextBox_1.Name = "TextBox11";
			global::System.Windows.Forms.Control control4 = this.TextBox_1;
			size = new global::System.Drawing.Size(44, 21);
			control4.Size = size;
			this.TextBox_1.TabIndex = 28;
			this.Label12.AutoSize = true;
			this.Label12.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label21 = this.Label12;
			location = new global::System.Drawing.Point(6, 17);
			label21.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label22 = this.Label12;
			size = new global::System.Drawing.Size(53, 12);
			label22.Size = size;
			this.Label12.TabIndex = 24;
			this.Label12.Text = "绘图比例";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label23 = this.Label1;
			location = new global::System.Drawing.Point(6, 86);
			label23.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label24 = this.Label1;
			size = new global::System.Drawing.Size(29, 12);
			label24.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "箍筋";
			this.Label13.AutoSize = true;
			global::System.Windows.Forms.Control label25 = this.Label13;
			location = new global::System.Drawing.Point(6, 63);
			label25.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label26 = this.Label13;
			size = new global::System.Drawing.Size(65, 12);
			label26.Size = size;
			this.Label13.TabIndex = 25;
			this.Label13.Text = "纵筋保护层";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label27 = this.Label4;
			location = new global::System.Drawing.Point(6, 109);
			label27.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label28 = this.Label4;
			size = new global::System.Drawing.Size(29, 12);
			label28.Size = size;
			this.Label4.TabIndex = 6;
			this.Label4.Text = "间距";
			this.ComboBox4.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox7 = this.ComboBox4;
			location = new global::System.Drawing.Point(85, 14);
			comboBox7.Location = location;
			this.ComboBox4.Name = "ComboBox4";
			global::System.Windows.Forms.Control comboBox8 = this.ComboBox4;
			size = new global::System.Drawing.Size(65, 20);
			comboBox8.Size = size;
			this.ComboBox4.TabIndex = 23;
			global::System.Windows.Forms.Control textBox11 = this.TextBox9;
			location = new global::System.Drawing.Point(85, 61);
			textBox11.Location = location;
			this.TextBox9.Name = "TextBox9";
			global::System.Windows.Forms.Control textBox12 = this.TextBox9;
			size = new global::System.Drawing.Size(65, 21);
			textBox12.Size = size;
			this.TextBox9.TabIndex = 26;
			this.ComboBox1.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox9 = this.ComboBox1;
			location = new global::System.Drawing.Point(85, 85);
			comboBox9.Location = location;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox10 = this.ComboBox1;
			size = new global::System.Drawing.Size(65, 20);
			comboBox10.Size = size;
			this.ComboBox1.TabIndex = 0;
			global::System.Windows.Forms.Control textBox13 = this.TextBox3;
			location = new global::System.Drawing.Point(85, 108);
			textBox13.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox14 = this.TextBox3;
			size = new global::System.Drawing.Size(65, 21);
			textBox14.Size = size;
			this.TextBox3.TabIndex = 7;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label29 = this.Label2;
			location = new global::System.Drawing.Point(10, 38);
			label29.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label30 = this.Label2;
			size = new global::System.Drawing.Size(29, 12);
			label30.Size = size;
			this.Label2.TabIndex = 28;
			this.Label2.Text = "面积";
			this.TextBox2.Enabled = false;
			global::System.Windows.Forms.Control textBox15 = this.TextBox2;
			location = new global::System.Drawing.Point(69, 35);
			textBox15.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox16 = this.TextBox2;
			size = new global::System.Drawing.Size(70, 21);
			textBox16.Size = size;
			this.TextBox2.TabIndex = 27;
			this.TextBox1.Enabled = false;
			global::System.Windows.Forms.Control textBox17 = this.TextBox1;
			location = new global::System.Drawing.Point(69, 12);
			textBox17.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox18 = this.TextBox1;
			size = new global::System.Drawing.Size(70, 21);
			textBox18.Size = size;
			this.TextBox1.TabIndex = 2;
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label31 = this.Label3;
			location = new global::System.Drawing.Point(10, 15);
			label31.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label32 = this.Label3;
			size = new global::System.Drawing.Size(29, 12);
			label32.Size = size;
			this.Label3.TabIndex = 5;
			this.Label3.Text = "截面";
			this.ListBox1.FormattingEnabled = true;
			this.ListBox1.ItemHeight = 12;
			global::System.Windows.Forms.Control listBox = this.ListBox1;
			location = new global::System.Drawing.Point(175, 167);
			listBox.Location = location;
			this.ListBox1.Name = "ListBox1";
			global::System.Windows.Forms.Control listBox2 = this.ListBox1;
			size = new global::System.Drawing.Size(223, 136);
			listBox2.Size = size;
			this.ListBox1.TabIndex = 30;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(326, 17);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(72, 22);
			button2.Size = size;
			this.Button1.TabIndex = 31;
			this.Button1.Text = "重新选择";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(326, 58);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(72, 22);
			button4.Size = size;
			this.Button2.TabIndex = 32;
			this.Button2.Text = "写计算书";
			this.Button2.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.TextBox1);
			this.GroupBox3.Controls.Add(this.Label3);
			this.GroupBox3.Controls.Add(this.Label2);
			this.GroupBox3.Controls.Add(this.TextBox2);
			this.GroupBox3.Controls.Add(this.Label7);
			this.GroupBox3.Controls.Add(this.TextBox4);
			this.GroupBox3.Controls.Add(this.Label5);
			this.GroupBox3.Controls.Add(this.TextBox5);
			this.GroupBox3.Controls.Add(this.Label6);
			this.GroupBox3.Controls.Add(this.TextBox6);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox3;
			location = new global::System.Drawing.Point(174, 7);
			groupBox5.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox3;
			size = new global::System.Drawing.Size(145, 133);
			groupBox6.Size = size;
			this.GroupBox3.TabIndex = 34;
			this.GroupBox3.TabStop = false;
			this.RadioButton1.AutoSize = true;
			global::System.Windows.Forms.Control radioButton = this.RadioButton1;
			location = new global::System.Drawing.Point(12, 310);
			radioButton.Location = location;
			this.RadioButton1.Name = "RadioButton1";
			global::System.Windows.Forms.Control radioButton2 = this.RadioButton1;
			size = new global::System.Drawing.Size(71, 16);
			radioButton2.Size = size;
			this.RadioButton1.TabIndex = 35;
			this.RadioButton1.TabStop = true;
			this.RadioButton1.Text = "按墙识别";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.RadioButton2.AutoSize = true;
			global::System.Windows.Forms.Control radioButton3 = this.RadioButton2;
			location = new global::System.Drawing.Point(97, 310);
			radioButton3.Location = location;
			this.RadioButton2.Name = "RadioButton2";
			global::System.Windows.Forms.Control radioButton4 = this.RadioButton2;
			size = new global::System.Drawing.Size(71, 16);
			radioButton4.Size = size;
			this.RadioButton2.TabIndex = 36;
			this.RadioButton2.Text = "按柱识别";
			this.RadioButton2.UseVisualStyleBackColor = true;
			this.Button3.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(252, 142);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(55, 22);
			button6.Size = size;
			this.Button3.TabIndex = 37;
			this.Button3.Text = "大箍筋";
			this.Button3.UseVisualStyleBackColor = true;
			this.Button5.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control button7 = this.Button5;
			location = new global::System.Drawing.Point(304, 142);
			button7.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button8 = this.Button5;
			size = new global::System.Drawing.Size(58, 22);
			button8.Size = size;
			this.Button5.TabIndex = 40;
			this.Button5.Text = "小箍筋";
			this.Button5.UseVisualStyleBackColor = true;
			this.Button6.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control button9 = this.Button6;
			location = new global::System.Drawing.Point(360, 142);
			button9.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button10 = this.Button6;
			size = new global::System.Drawing.Size(37, 22);
			button10.Size = size;
			this.Button6.TabIndex = 42;
			this.Button6.Text = "拉筋";
			this.Button6.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button11 = this.Button7;
			location = new global::System.Drawing.Point(141, 210);
			button11.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button12 = this.Button7;
			size = new global::System.Drawing.Size(21, 21);
			button12.Size = size;
			this.Button7.TabIndex = 43;
			this.Button7.Text = ".";
			this.Button7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control5 = this.TextBox_2;
			location = new global::System.Drawing.Point(174, 308);
			control5.Location = location;
			this.TextBox_2.Name = "TextBox12";
			global::System.Windows.Forms.Control control6 = this.TextBox_2;
			size = new global::System.Drawing.Size(72, 21);
			control6.Size = size;
			this.TextBox_2.TabIndex = 44;
			this.TextBox_2.Text = "200";
			global::System.Windows.Forms.Control button13 = this.Button4;
			location = new global::System.Drawing.Point(252, 306);
			button13.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button14 = this.Button4;
			size = new global::System.Drawing.Size(67, 24);
			button14.Size = size;
			this.Button4.TabIndex = 45;
			this.Button4.Text = "加一肢";
			this.Button4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button15 = this.Button8;
			location = new global::System.Drawing.Point(325, 306);
			button15.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button16 = this.Button8;
			size = new global::System.Drawing.Size(73, 24);
			button16.Size = size;
			this.Button8.TabIndex = 46;
			this.Button8.Text = "减一肢";
			this.Button8.UseVisualStyleBackColor = true;
			this.Button9.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control button17 = this.Button9;
			location = new global::System.Drawing.Point(173, 142);
			button17.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button18 = this.Button9;
			size = new global::System.Drawing.Size(64, 22);
			button18.Size = size;
			this.Button9.TabIndex = 47;
			this.Button9.Text = "墙柱轮廓";
			this.Button9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button19 = this.Button10;
			location = new global::System.Drawing.Point(326, 91);
			button19.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button20 = this.Button10;
			size = new global::System.Drawing.Size(72, 22);
			button20.Size = size;
			this.Button10.TabIndex = 48;
			this.Button10.Text = "简写";
			this.Button10.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control7 = this.TextBox_3;
			location = new global::System.Drawing.Point(373, 119);
			control7.Location = location;
			this.TextBox_3.Name = "TextBox13";
			global::System.Windows.Forms.Control control8 = this.TextBox_3;
			size = new global::System.Drawing.Size(25, 21);
			control8.Size = size;
			this.TextBox_3.TabIndex = 49;
			this.TextBox_3.Text = "10";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(402, 338);
			this.ClientSize = size;
			this.Controls.Add(this.TextBox_3);
			this.Controls.Add(this.Button10);
			this.Controls.Add(this.Button9);
			this.Controls.Add(this.Button8);
			this.Controls.Add(this.Button4);
			this.Controls.Add(this.TextBox_2);
			this.Controls.Add(this.Button7);
			this.Controls.Add(this.Button6);
			this.Controls.Add(this.Button5);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.RadioButton2);
			this.Controls.Add(this.RadioButton1);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.ListBox1);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.TextBox8);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.Name = "TcAsv_Frm";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "体积配箍率";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
