namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcCGB_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.TableLayoutPanel1 = new global::System.Windows.Forms.TableLayoutPanel();
			this.OK_Button = new global::System.Windows.Forms.Button();
			this.Cancel_Button = new global::System.Windows.Forms.Button();
			this.DataGridView1 = new global::System.Windows.Forms.DataGridView();
			this.Column1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox3 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox4 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox5 = new global::System.Windows.Forms.ComboBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.TableLayoutPanel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).BeginInit();
			this.SuspendLayout();
			this.TableLayoutPanel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.TableLayoutPanel1.ColumnCount = 2;
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.TableLayoutPanel1.Controls.Add(this.OK_Button, 0, 0);
			this.TableLayoutPanel1.Controls.Add(this.Cancel_Button, 1, 0);
			global::System.Windows.Forms.Control tableLayoutPanel = this.TableLayoutPanel1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(369, 408);
			tableLayoutPanel.Location = location;
			global::System.Windows.Forms.Control tableLayoutPanel2 = this.TableLayoutPanel1;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(4);
			tableLayoutPanel2.Margin = margin;
			this.TableLayoutPanel1.Name = "TableLayoutPanel1";
			this.TableLayoutPanel1.RowCount = 1;
			this.TableLayoutPanel1.RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			global::System.Windows.Forms.Control tableLayoutPanel3 = this.TableLayoutPanel1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(195, 45);
			tableLayoutPanel3.Size = size;
			this.TableLayoutPanel1.TabIndex = 0;
			this.OK_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			global::System.Windows.Forms.Control ok_Button = this.OK_Button;
			location = new global::System.Drawing.Point(4, 4);
			ok_Button.Location = location;
			global::System.Windows.Forms.Control ok_Button2 = this.OK_Button;
			margin = new global::System.Windows.Forms.Padding(4);
			ok_Button2.Margin = margin;
			this.OK_Button.Name = "OK_Button";
			global::System.Windows.Forms.Control ok_Button3 = this.OK_Button;
			size = new global::System.Drawing.Size(89, 36);
			ok_Button3.Size = size;
			this.OK_Button.TabIndex = 0;
			this.OK_Button.Text = "确定";
			this.Cancel_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Cancel_Button.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			global::System.Windows.Forms.Control cancel_Button = this.Cancel_Button;
			location = new global::System.Drawing.Point(101, 4);
			cancel_Button.Location = location;
			global::System.Windows.Forms.Control cancel_Button2 = this.Cancel_Button;
			margin = new global::System.Windows.Forms.Padding(4);
			cancel_Button2.Margin = margin;
			this.Cancel_Button.Name = "Cancel_Button";
			global::System.Windows.Forms.Control cancel_Button3 = this.Cancel_Button;
			size = new global::System.Drawing.Size(89, 36);
			cancel_Button3.Size = size;
			this.Cancel_Button.TabIndex = 1;
			this.Cancel_Button.Text = "取消";
			this.DataGridView1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DataGridView1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column1,
				this.Column2,
				this.Column3,
				this.Column4,
				this.Column5
			});
			global::System.Windows.Forms.Control dataGridView = this.DataGridView1;
			location = new global::System.Drawing.Point(16, 48);
			dataGridView.Location = location;
			global::System.Windows.Forms.Control dataGridView2 = this.DataGridView1;
			margin = new global::System.Windows.Forms.Padding(4);
			dataGridView2.Margin = margin;
			this.DataGridView1.Name = "DataGridView1";
			this.DataGridView1.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView3 = this.DataGridView1;
			size = new global::System.Drawing.Size(548, 298);
			dataGridView3.Size = size;
			this.DataGridView1.TabIndex = 1;
			this.Column1.HeaderText = "层号";
			this.Column1.Name = "Column1";
			this.Column1.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column1.Width = 75;
			this.Column2.HeaderText = "层高";
			this.Column2.Name = "Column2";
			this.Column2.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column2.Width = 75;
			this.Column3.HeaderText = "标高";
			this.Column3.Name = "Column3";
			this.Column3.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column3.Width = 75;
			this.Column4.HeaderText = "墙柱砼";
			this.Column4.Name = "Column4";
			this.Column4.Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.Column4.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column4.Width = 75;
			this.Column5.HeaderText = "梁板砼";
			this.Column5.Name = "Column5";
			this.Column5.Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.Column5.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column5.Width = 75;
			this.ComboBox1.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox = this.ComboBox1;
			location = new global::System.Drawing.Point(20, 380);
			comboBox.Location = location;
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox1;
			margin = new global::System.Windows.Forms.Padding(4);
			comboBox2.Margin = margin;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox3 = this.ComboBox1;
			size = new global::System.Drawing.Size(63, 23);
			comboBox3.Size = size;
			this.ComboBox1.TabIndex = 2;
			this.ComboBox2.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox4 = this.ComboBox2;
			location = new global::System.Drawing.Point(92, 380);
			comboBox4.Location = location;
			global::System.Windows.Forms.Control comboBox5 = this.ComboBox2;
			margin = new global::System.Windows.Forms.Padding(4);
			comboBox5.Margin = margin;
			this.ComboBox2.Name = "ComboBox2";
			global::System.Windows.Forms.Control comboBox6 = this.ComboBox2;
			size = new global::System.Drawing.Size(87, 23);
			comboBox6.Size = size;
			this.ComboBox2.TabIndex = 3;
			this.ComboBox3.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox7 = this.ComboBox3;
			location = new global::System.Drawing.Point(188, 380);
			comboBox7.Location = location;
			global::System.Windows.Forms.Control comboBox8 = this.ComboBox3;
			margin = new global::System.Windows.Forms.Padding(4);
			comboBox8.Margin = margin;
			this.ComboBox3.Name = "ComboBox3";
			global::System.Windows.Forms.Control comboBox9 = this.ComboBox3;
			size = new global::System.Drawing.Size(87, 23);
			comboBox9.Size = size;
			this.ComboBox3.TabIndex = 4;
			this.ComboBox4.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox10 = this.ComboBox4;
			location = new global::System.Drawing.Point(284, 380);
			comboBox10.Location = location;
			global::System.Windows.Forms.Control comboBox11 = this.ComboBox4;
			margin = new global::System.Windows.Forms.Padding(4);
			comboBox11.Margin = margin;
			this.ComboBox4.Name = "ComboBox4";
			global::System.Windows.Forms.Control comboBox12 = this.ComboBox4;
			size = new global::System.Drawing.Size(92, 23);
			comboBox12.Size = size;
			this.ComboBox4.TabIndex = 5;
			this.ComboBox5.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox13 = this.ComboBox5;
			location = new global::System.Drawing.Point(385, 380);
			comboBox13.Location = location;
			global::System.Windows.Forms.Control comboBox14 = this.ComboBox5;
			margin = new global::System.Windows.Forms.Padding(4);
			comboBox14.Margin = margin;
			this.ComboBox5.Name = "ComboBox5";
			global::System.Windows.Forms.Control comboBox15 = this.ComboBox5;
			size = new global::System.Drawing.Size(84, 23);
			comboBox15.Size = size;
			this.ComboBox5.TabIndex = 6;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(16, 412);
			button.Location = location;
			global::System.Windows.Forms.Control button2 = this.Button1;
			margin = new global::System.Windows.Forms.Padding(4);
			button2.Margin = margin;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button3 = this.Button1;
			size = new global::System.Drawing.Size(64, 35);
			button3.Size = size;
			this.Button1.TabIndex = 8;
			this.Button1.Text = "添加";
			this.Button1.UseVisualStyleBackColor = true;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(17, 355);
			label.Location = location;
			global::System.Windows.Forms.Control label2 = this.Label1;
			margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label2.Margin = margin;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label3 = this.Label1;
			size = new global::System.Drawing.Size(37, 15);
			label3.Size = size;
			this.Label1.TabIndex = 9;
			this.Label1.Text = "层数";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label4 = this.Label2;
			location = new global::System.Drawing.Point(89, 355);
			label4.Location = location;
			global::System.Windows.Forms.Control label5 = this.Label2;
			margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label5.Margin = margin;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label6 = this.Label2;
			size = new global::System.Drawing.Size(37, 15);
			label6.Size = size;
			this.Label2.TabIndex = 10;
			this.Label2.Text = "层高";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label3;
			location = new global::System.Drawing.Point(188, 355);
			label7.Location = location;
			global::System.Windows.Forms.Control label8 = this.Label3;
			margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label8.Margin = margin;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label9 = this.Label3;
			size = new global::System.Drawing.Size(67, 15);
			label9.Size = size;
			this.Label3.TabIndex = 11;
			this.Label3.Text = "起始标高";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label10 = this.Label4;
			location = new global::System.Drawing.Point(281, 355);
			label10.Location = location;
			global::System.Windows.Forms.Control label11 = this.Label4;
			margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label11.Margin = margin;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label12 = this.Label4;
			size = new global::System.Drawing.Size(52, 15);
			label12.Size = size;
			this.Label4.TabIndex = 12;
			this.Label4.Text = "墙柱砼";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label5;
			location = new global::System.Drawing.Point(383, 355);
			label13.Location = location;
			global::System.Windows.Forms.Control label14 = this.Label5;
			margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			label14.Margin = margin;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label15 = this.Label5;
			size = new global::System.Drawing.Size(52, 15);
			label15.Size = size;
			this.Label5.TabIndex = 13;
			this.Label5.Text = "梁板砼";
			this.CheckBox1.AutoSize = true;
			global::System.Windows.Forms.Control checkBox = this.CheckBox1;
			location = new global::System.Drawing.Point(485, 15);
			checkBox.Location = location;
			global::System.Windows.Forms.Control checkBox2 = this.CheckBox1;
			margin = new global::System.Windows.Forms.Padding(4);
			checkBox2.Margin = margin;
			this.CheckBox1.Name = "CheckBox1";
			global::System.Windows.Forms.Control checkBox3 = this.CheckBox1;
			size = new global::System.Drawing.Size(74, 19);
			checkBox3.Size = size;
			this.CheckBox1.TabIndex = 14;
			this.CheckBox1.Text = "墙柱砼";
			this.CheckBox1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button4 = this.Button2;
			location = new global::System.Drawing.Point(176, 411);
			button4.Location = location;
			global::System.Windows.Forms.Control button5 = this.Button2;
			margin = new global::System.Windows.Forms.Padding(4);
			button5.Margin = margin;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button6 = this.Button2;
			size = new global::System.Drawing.Size(64, 35);
			button6.Size = size;
			this.Button2.TabIndex = 15;
			this.Button2.Text = "清除";
			this.Button2.UseVisualStyleBackColor = true;
			this.CheckBox2.AutoSize = true;
			global::System.Windows.Forms.Control checkBox4 = this.CheckBox2;
			location = new global::System.Drawing.Point(17, 15);
			checkBox4.Location = location;
			global::System.Windows.Forms.Control checkBox5 = this.CheckBox2;
			margin = new global::System.Windows.Forms.Padding(4);
			checkBox5.Margin = margin;
			this.CheckBox2.Name = "CheckBox2";
			global::System.Windows.Forms.Control checkBox6 = this.CheckBox2;
			size = new global::System.Drawing.Size(89, 19);
			checkBox6.Size = size;
			this.CheckBox2.TabIndex = 16;
			this.CheckBox2.Text = "上次记录";
			this.CheckBox2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button7 = this.Button3;
			location = new global::System.Drawing.Point(88, 411);
			button7.Location = location;
			global::System.Windows.Forms.Control button8 = this.Button3;
			margin = new global::System.Windows.Forms.Padding(4);
			button8.Margin = margin;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button9 = this.Button3;
			size = new global::System.Drawing.Size(80, 35);
			button9.Size = size;
			this.Button3.TabIndex = 17;
			this.Button3.Text = "地下室";
			this.Button3.UseVisualStyleBackColor = true;
			this.AcceptButton = this.OK_Button;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(8f, 15f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.Cancel_Button;
			size = new global::System.Drawing.Size(579, 450);
			this.ClientSize = size;
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.CheckBox2);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.CheckBox1);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.ComboBox5);
			this.Controls.Add(this.ComboBox4);
			this.Controls.Add(this.ComboBox3);
			this.Controls.Add(this.ComboBox2);
			this.Controls.Add(this.ComboBox1);
			this.Controls.Add(this.DataGridView1);
			this.Controls.Add(this.TableLayoutPanel1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			margin = new global::System.Windows.Forms.Padding(4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "TcCGB_Frm";
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "层高表";
			this.TableLayoutPanel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
