namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class tcCiKu_frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.SplitContainer1 = new global::System.Windows.Forms.SplitContainer();
			this.TreeView1 = new global::System.Windows.Forms.TreeView();
			this.SplitContainer2 = new global::System.Windows.Forms.SplitContainer();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.SplitContainer3 = new global::System.Windows.Forms.SplitContainer();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.SplitContainer1.Panel1.SuspendLayout();
			this.SplitContainer1.Panel2.SuspendLayout();
			this.SplitContainer1.SuspendLayout();
			this.SplitContainer2.Panel1.SuspendLayout();
			this.SplitContainer2.Panel2.SuspendLayout();
			this.SplitContainer2.SuspendLayout();
			this.SplitContainer3.Panel1.SuspendLayout();
			this.SplitContainer3.Panel2.SuspendLayout();
			this.SplitContainer3.SuspendLayout();
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			this.SplitContainer1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.SplitContainer1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer = this.SplitContainer1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			splitContainer.Location = location;
			this.SplitContainer1.Name = "SplitContainer1";
			this.SplitContainer1.Panel1.Controls.Add(this.TreeView1);
			this.SplitContainer1.Panel2.Controls.Add(this.SplitContainer2);
			this.SplitContainer1.Panel2.Controls.Add(this.Panel1);
			global::System.Windows.Forms.Control splitContainer2 = this.SplitContainer1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(592, 387);
			splitContainer2.Size = size;
			this.SplitContainer1.SplitterDistance = 203;
			this.SplitContainer1.SplitterWidth = 8;
			this.SplitContainer1.TabIndex = 27;
			this.TreeView1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TreeView1.CheckBoxes = true;
			this.TreeView1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.TreeView1.LabelEdit = true;
			global::System.Windows.Forms.Control treeView = this.TreeView1;
			location = new global::System.Drawing.Point(0, 0);
			treeView.Location = location;
			this.TreeView1.Name = "TreeView1";
			global::System.Windows.Forms.Control treeView2 = this.TreeView1;
			size = new global::System.Drawing.Size(201, 385);
			treeView2.Size = size;
			this.TreeView1.TabIndex = 27;
			this.SplitContainer2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.SplitContainer2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer3 = this.SplitContainer2;
			location = new global::System.Drawing.Point(0, 31);
			splitContainer3.Location = location;
			this.SplitContainer2.Name = "SplitContainer2";
			this.SplitContainer2.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			this.SplitContainer2.Panel1.Controls.Add(this.TextBox1);
			this.SplitContainer2.Panel2.Controls.Add(this.SplitContainer3);
			global::System.Windows.Forms.Control splitContainer4 = this.SplitContainer2;
			size = new global::System.Drawing.Size(381, 356);
			splitContainer4.Size = size;
			this.SplitContainer2.SplitterDistance = 77;
			this.SplitContainer2.SplitterWidth = 8;
			this.SplitContainer2.TabIndex = 29;
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(0, 0);
			textBox.Location = location;
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(379, 75);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 29;
			this.SplitContainer3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.SplitContainer3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer5 = this.SplitContainer3;
			location = new global::System.Drawing.Point(0, 0);
			splitContainer5.Location = location;
			this.SplitContainer3.Name = "SplitContainer3";
			this.SplitContainer3.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			this.SplitContainer3.Panel1.Controls.Add(this.TextBox2);
			this.SplitContainer3.Panel2.Controls.Add(this.TextBox3);
			global::System.Windows.Forms.Control splitContainer6 = this.SplitContainer3;
			size = new global::System.Drawing.Size(381, 271);
			splitContainer6.Size = size;
			this.SplitContainer3.SplitterDistance = 121;
			this.SplitContainer3.SplitterWidth = 8;
			this.SplitContainer3.TabIndex = 31;
			this.TextBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			location = new global::System.Drawing.Point(0, 0);
			textBox3.Location = location;
			this.TextBox2.Multiline = true;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new global::System.Drawing.Size(379, 119);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 31;
			this.TextBox3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control textBox5 = this.TextBox3;
			location = new global::System.Drawing.Point(0, 0);
			textBox5.Location = location;
			this.TextBox3.Multiline = true;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox6 = this.TextBox3;
			size = new global::System.Drawing.Size(379, 140);
			textBox6.Size = size;
			this.TextBox3.TabIndex = 32;
			this.Panel1.Controls.Add(this.Button1);
			this.Panel1.Controls.Add(this.Button6);
			this.Panel1.Controls.Add(this.Button3);
			this.Panel1.Controls.Add(this.Button5);
			this.Panel1.Controls.Add(this.Button2);
			this.Panel1.Controls.Add(this.Button4);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			global::System.Windows.Forms.Control panel = this.Panel1;
			location = new global::System.Drawing.Point(0, 0);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(381, 31);
			panel2.Size = size;
			this.Panel1.TabIndex = 0;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(144, 0);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(75, 31);
			button2.Size = size;
			this.Button1.TabIndex = 36;
			this.Button1.Text = "添加跟目录";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button6;
			location = new global::System.Drawing.Point(214, 0);
			button3.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button4 = this.Button6;
			size = new global::System.Drawing.Size(49, 31);
			button4.Size = size;
			this.Button6.TabIndex = 40;
			this.Button6.Text = "编辑";
			this.Button6.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(98, 0);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(49, 31);
			button6.Size = size;
			this.Button3.TabIndex = 37;
			this.Button3.Text = "添加";
			this.Button3.UseVisualStyleBackColor = true;
			this.Button5.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 134);
			this.Button5.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control button7 = this.Button5;
			location = new global::System.Drawing.Point(0, 0);
			button7.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button8 = this.Button5;
			size = new global::System.Drawing.Size(49, 31);
			button8.Size = size;
			this.Button5.TabIndex = 35;
			this.Button5.Text = "绘图";
			this.Button5.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button9 = this.Button2;
			location = new global::System.Drawing.Point(258, 0);
			button9.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button10 = this.Button2;
			size = new global::System.Drawing.Size(49, 31);
			button10.Size = size;
			this.Button2.TabIndex = 38;
			this.Button2.Text = "删除";
			this.Button2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button11 = this.Button4;
			location = new global::System.Drawing.Point(49, 0);
			button11.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button12 = this.Button4;
			size = new global::System.Drawing.Size(49, 31);
			button12.Size = size;
			this.Button4.TabIndex = 39;
			this.Button4.Text = "保存";
			this.Button4.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(592, 387);
			this.ClientSize = size;
			this.Controls.Add(this.SplitContainer1);
			this.Name = "CiKu_frm";
			this.Text = "词库";
			this.SplitContainer1.Panel1.ResumeLayout(false);
			this.SplitContainer1.Panel2.ResumeLayout(false);
			this.SplitContainer1.ResumeLayout(false);
			this.SplitContainer2.Panel1.ResumeLayout(false);
			this.SplitContainer2.Panel1.PerformLayout();
			this.SplitContainer2.Panel2.ResumeLayout(false);
			this.SplitContainer2.ResumeLayout(false);
			this.SplitContainer3.Panel1.ResumeLayout(false);
			this.SplitContainer3.Panel1.PerformLayout();
			this.SplitContainer3.Panel2.ResumeLayout(false);
			this.SplitContainer3.Panel2.PerformLayout();
			this.SplitContainer3.ResumeLayout(false);
			this.Panel1.ResumeLayout(false);
			this.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
