namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcDJ_frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.jipAtgRsh != null)
			{
				this.jipAtgRsh.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.jipAtgRsh = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::田草CAD工具箱_For2014.TcDJ_frm));
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.TextBox9 = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TextBox8 = new global::System.Windows.Forms.TextBox();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.TextBox_4 = new global::System.Windows.Forms.TextBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.TextBox_3 = new global::System.Windows.Forms.TextBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextBox_2 = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.TextBox_0 = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.TextBox_1 = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.jipAtgRsh);
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.SuspendLayout();
			this.GroupBox1.Controls.Add(this.TextBox1);
			this.GroupBox1.Controls.Add(this.CheckBox1);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(1, 2);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(234, 43);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "柱子";
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(6, 14);
			textBox.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(62, 21);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 1;
			this.TextBox1.Text = "450x450";
			this.CheckBox1.AutoSize = true;
			global::System.Windows.Forms.Control checkBox = this.CheckBox1;
			location = new global::System.Drawing.Point(74, 16);
			checkBox.Location = location;
			this.CheckBox1.Name = "CheckBox1";
			global::System.Windows.Forms.Control checkBox2 = this.CheckBox1;
			size = new global::System.Drawing.Size(48, 16);
			checkBox2.Size = size;
			this.CheckBox1.TabIndex = 1;
			this.CheckBox1.Text = "圆柱";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.TextBox2);
			this.GroupBox2.Controls.Add(this.Label2);
			this.GroupBox2.Controls.Add(this.Label1);
			this.GroupBox2.Controls.Add(this.TextBox7);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			location = new global::System.Drawing.Point(1, 51);
			groupBox3.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(122, 70);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 1;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "基础";
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			location = new global::System.Drawing.Point(39, 40);
			textBox3.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new global::System.Drawing.Size(75, 21);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 5;
			this.TextBox2.Text = "300+200";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label2;
			location = new global::System.Drawing.Point(4, 43);
			label.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label2 = this.Label2;
			size = new global::System.Drawing.Size(29, 12);
			label2.Size = size;
			this.Label2.TabIndex = 4;
			this.Label2.Text = "变阶";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label1;
			location = new global::System.Drawing.Point(4, 19);
			label3.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label4 = this.Label1;
			size = new global::System.Drawing.Size(29, 12);
			label4.Size = size;
			this.Label1.TabIndex = 3;
			this.Label1.Text = "长宽";
			global::System.Windows.Forms.Control textBox5 = this.TextBox7;
			location = new global::System.Drawing.Point(39, 16);
			textBox5.Location = location;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox6 = this.TextBox7;
			size = new global::System.Drawing.Size(75, 21);
			textBox6.Size = size;
			this.TextBox7.TabIndex = 2;
			this.TextBox7.Text = "2000x2000";
			this.GroupBox3.Controls.Add(this.TextBox3);
			this.GroupBox3.Controls.Add(this.Label3);
			this.GroupBox3.Controls.Add(this.Label4);
			this.GroupBox3.Controls.Add(this.TextBox4);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox3;
			location = new global::System.Drawing.Point(130, 51);
			groupBox5.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox3;
			size = new global::System.Drawing.Size(105, 70);
			groupBox6.Size = size;
			this.GroupBox3.TabIndex = 2;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "配筋";
			global::System.Windows.Forms.Control textBox7 = this.TextBox3;
			location = new global::System.Drawing.Point(37, 14);
			textBox7.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox8 = this.TextBox3;
			size = new global::System.Drawing.Size(62, 21);
			textBox8.Size = size;
			this.TextBox3.TabIndex = 5;
			this.TextBox3.Text = "C12@150";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new global::System.Drawing.Point(14, 43);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(11, 12);
			label6.Size = size;
			this.Label3.TabIndex = 4;
			this.Label3.Text = "Y";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label4;
			location = new global::System.Drawing.Point(14, 17);
			label7.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(11, 12);
			label8.Size = size;
			this.Label4.TabIndex = 3;
			this.Label4.Text = "X";
			global::System.Windows.Forms.Control textBox9 = this.TextBox4;
			location = new global::System.Drawing.Point(37, 40);
			textBox9.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox10 = this.TextBox4;
			size = new global::System.Drawing.Size(62, 21);
			textBox10.Size = size;
			this.TextBox4.TabIndex = 2;
			this.TextBox4.Text = "C12@150";
			this.GroupBox4.Controls.Add(this.TextBox5);
			this.GroupBox4.Controls.Add(this.Label5);
			this.GroupBox4.Controls.Add(this.Label6);
			this.GroupBox4.Controls.Add(this.TextBox6);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox4;
			location = new global::System.Drawing.Point(7, 136);
			groupBox7.Location = location;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox4;
			size = new global::System.Drawing.Size(106, 70);
			groupBox8.Size = size;
			this.GroupBox4.TabIndex = 3;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "偏心";
			global::System.Windows.Forms.Control textBox11 = this.TextBox5;
			location = new global::System.Drawing.Point(37, 14);
			textBox11.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox12 = this.TextBox5;
			size = new global::System.Drawing.Size(71, 21);
			textBox12.Size = size;
			this.TextBox5.TabIndex = 5;
			this.TextBox5.Text = "0";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label5;
			location = new global::System.Drawing.Point(6, 17);
			label9.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label10 = this.Label5;
			size = new global::System.Drawing.Size(29, 12);
			label10.Size = size;
			this.Label5.TabIndex = 4;
			this.Label5.Text = "水平";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label6;
			location = new global::System.Drawing.Point(6, 41);
			label11.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label12 = this.Label6;
			size = new global::System.Drawing.Size(29, 12);
			label12.Size = size;
			this.Label6.TabIndex = 3;
			this.Label6.Text = "垂直";
			global::System.Windows.Forms.Control textBox13 = this.TextBox6;
			location = new global::System.Drawing.Point(37, 41);
			textBox13.Location = location;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox14 = this.TextBox6;
			size = new global::System.Drawing.Size(71, 21);
			textBox14.Size = size;
			this.TextBox6.TabIndex = 2;
			this.TextBox6.Text = "0";
			this.GroupBox5.Controls.Add(this.TextBox9);
			this.GroupBox5.Controls.Add(this.Label8);
			this.GroupBox5.Controls.Add(this.Label7);
			this.GroupBox5.Controls.Add(this.TextBox8);
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox5;
			location = new global::System.Drawing.Point(121, 136);
			groupBox9.Location = location;
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox5;
			size = new global::System.Drawing.Size(114, 70);
			groupBox10.Size = size;
			this.GroupBox5.TabIndex = 5;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "其他";
			global::System.Windows.Forms.Control textBox15 = this.TextBox9;
			location = new global::System.Drawing.Point(37, 41);
			textBox15.Location = location;
			this.TextBox9.Name = "TextBox9";
			global::System.Windows.Forms.Control textBox16 = this.TextBox9;
			size = new global::System.Drawing.Size(71, 21);
			textBox16.Size = size;
			this.TextBox9.TabIndex = 8;
			this.TextBox9.Text = "-1.500";
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label8;
			location = new global::System.Drawing.Point(6, 42);
			label13.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label14 = this.Label8;
			size = new global::System.Drawing.Size(29, 12);
			label14.Size = size;
			this.Label8.TabIndex = 7;
			this.Label8.Text = "标高";
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label7;
			location = new global::System.Drawing.Point(6, 17);
			label15.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label16 = this.Label7;
			size = new global::System.Drawing.Size(29, 12);
			label16.Size = size;
			this.Label7.TabIndex = 6;
			this.Label7.Text = "比例";
			global::System.Windows.Forms.Control textBox17 = this.TextBox8;
			location = new global::System.Drawing.Point(37, 14);
			textBox17.Location = location;
			this.TextBox8.Name = "TextBox8";
			global::System.Windows.Forms.Control textBox18 = this.TextBox8;
			size = new global::System.Drawing.Size(71, 21);
			textBox18.Size = size;
			this.TextBox8.TabIndex = 5;
			this.TextBox8.Text = "25";
			this.GroupBox6.Controls.Add(this.Button1);
			this.GroupBox6.Controls.Add(this.Button3);
			this.GroupBox6.Controls.Add(this.TextBox_4);
			this.GroupBox6.Controls.Add(this.Label16);
			this.GroupBox6.Controls.Add(this.TextBox_3);
			this.GroupBox6.Controls.Add(this.Label15);
			this.GroupBox6.Controls.Add(this.Button2);
			this.GroupBox6.Controls.Add(this.ComboBox2);
			this.GroupBox6.Controls.Add(this.Label14);
			this.GroupBox6.Controls.Add(this.ComboBox1);
			this.GroupBox6.Controls.Add(this.Label12);
			this.GroupBox6.Controls.Add(this.TextBox_2);
			this.GroupBox6.Controls.Add(this.Label11);
			this.GroupBox6.Controls.Add(this.TextBox_0);
			this.GroupBox6.Controls.Add(this.Label10);
			this.GroupBox6.Controls.Add(this.TextBox_1);
			this.GroupBox6.Controls.Add(this.Label9);
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox6;
			location = new global::System.Drawing.Point(242, 2);
			groupBox11.Location = location;
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox6;
			size = new global::System.Drawing.Size(155, 205);
			groupBox12.Size = size;
			this.GroupBox6.TabIndex = 6;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "计算";
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(106, 170);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(39, 23);
			button2.Size = size;
			this.Button1.TabIndex = 20;
			this.Button1.Text = "绘图";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button3;
			location = new global::System.Drawing.Point(58, 170);
			button3.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button4 = this.Button3;
			size = new global::System.Drawing.Size(39, 23);
			button4.Size = size;
			this.Button3.TabIndex = 13;
			this.Button3.Text = "验算";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control = this.TextBox_4;
			location = new global::System.Drawing.Point(93, 92);
			control.Location = location;
			this.TextBox_4.Name = "TextBox15";
			global::System.Windows.Forms.Control control2 = this.TextBox_4;
			size = new global::System.Drawing.Size(52, 21);
			control2.Size = size;
			this.TextBox_4.TabIndex = 17;
			this.TextBox_4.Text = "1.0";
			this.Label16.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label16;
			location = new global::System.Drawing.Point(8, 94);
			label17.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label18 = this.Label16;
			size = new global::System.Drawing.Size(41, 12);
			label18.Size = size;
			this.Label16.TabIndex = 16;
			this.Label16.Text = "长宽比";
			global::System.Windows.Forms.Control control3 = this.TextBox_3;
			location = new global::System.Drawing.Point(93, 71);
			control3.Location = location;
			this.TextBox_3.Name = "TextBox14";
			global::System.Windows.Forms.Control control4 = this.TextBox_3;
			size = new global::System.Drawing.Size(52, 21);
			control4.Size = size;
			this.TextBox_3.TabIndex = 15;
			this.TextBox_3.Text = "1.0";
			this.Label15.AutoSize = true;
			global::System.Windows.Forms.Control label19 = this.Label15;
			location = new global::System.Drawing.Point(8, 74);
			label19.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label20 = this.Label15;
			size = new global::System.Drawing.Size(47, 12);
			label20.Size = size;
			this.Label15.TabIndex = 14;
			this.Label15.Text = "埋深(m)";
			global::System.Windows.Forms.Control button5 = this.Button2;
			location = new global::System.Drawing.Point(10, 170);
			button5.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button6 = this.Button2;
			size = new global::System.Drawing.Size(39, 23);
			button6.Size = size;
			this.Button2.TabIndex = 12;
			this.Button2.Text = "设计";
			this.Button2.UseVisualStyleBackColor = true;
			this.ComboBox2.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox = this.ComboBox2;
			location = new global::System.Drawing.Point(70, 136);
			comboBox.Location = location;
			this.ComboBox2.Name = "ComboBox2";
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox2;
			size = new global::System.Drawing.Size(75, 20);
			comboBox2.Size = size;
			this.ComboBox2.TabIndex = 11;
			this.ComboBox2.Text = "C30";
			this.Label14.AutoSize = true;
			global::System.Windows.Forms.Control label21 = this.Label14;
			location = new global::System.Drawing.Point(8, 136);
			label21.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label22 = this.Label14;
			size = new global::System.Drawing.Size(41, 12);
			label22.Size = size;
			this.Label14.TabIndex = 10;
			this.Label14.Text = "混凝土";
			this.ComboBox1.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox3 = this.ComboBox1;
			location = new global::System.Drawing.Point(70, 116);
			comboBox3.Location = location;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox4 = this.ComboBox1;
			size = new global::System.Drawing.Size(75, 20);
			comboBox4.Size = size;
			this.ComboBox1.TabIndex = 9;
			this.ComboBox1.Text = "HRB300";
			this.Label12.AutoSize = true;
			global::System.Windows.Forms.Control label23 = this.Label12;
			location = new global::System.Drawing.Point(8, 116);
			label23.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label24 = this.Label12;
			size = new global::System.Drawing.Size(29, 12);
			label24.Size = size;
			this.Label12.TabIndex = 8;
			this.Label12.Text = "钢筋";
			global::System.Windows.Forms.Control control5 = this.TextBox_2;
			location = new global::System.Drawing.Point(93, 50);
			control5.Location = location;
			this.TextBox_2.Name = "TextBox12";
			global::System.Windows.Forms.Control control6 = this.TextBox_2;
			size = new global::System.Drawing.Size(52, 21);
			control6.Size = size;
			this.TextBox_2.TabIndex = 5;
			this.TextBox_2.Text = "100";
			this.Label11.AutoSize = true;
			global::System.Windows.Forms.Control label25 = this.Label11;
			location = new global::System.Drawing.Point(8, 54);
			label25.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label26 = this.Label11;
			size = new global::System.Drawing.Size(65, 12);
			label26.Size = size;
			this.Label11.TabIndex = 4;
			this.Label11.Text = "轴力Nk(KN)";
			global::System.Windows.Forms.Control control7 = this.TextBox_0;
			location = new global::System.Drawing.Point(93, 29);
			control7.Location = location;
			this.TextBox_0.Name = "TextBox11";
			global::System.Windows.Forms.Control control8 = this.TextBox_0;
			size = new global::System.Drawing.Size(52, 21);
			control8.Size = size;
			this.TextBox_0.TabIndex = 3;
			this.TextBox_0.Text = "100";
			this.Label10.AutoSize = true;
			global::System.Windows.Forms.Control label27 = this.Label10;
			location = new global::System.Drawing.Point(8, 34);
			label27.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label28 = this.Label10;
			size = new global::System.Drawing.Size(77, 12);
			label28.Size = size;
			this.Label10.TabIndex = 2;
			this.Label10.Text = "弯矩Mk(KN.m)";
			global::System.Windows.Forms.Control control9 = this.TextBox_1;
			location = new global::System.Drawing.Point(106, 8);
			control9.Location = location;
			this.TextBox_1.Name = "TextBox10";
			global::System.Windows.Forms.Control control10 = this.TextBox_1;
			size = new global::System.Drawing.Size(39, 21);
			control10.Size = size;
			this.TextBox_1.TabIndex = 1;
			this.TextBox_1.Text = "100";
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label29 = this.Label9;
			location = new global::System.Drawing.Point(8, 14);
			label29.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label30 = this.Label9;
			size = new global::System.Drawing.Size(95, 12);
			label30.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "修正后地载(KPa)";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(401, 212);
			this.ClientSize = size;
			this.Controls.Add(this.GroupBox6);
			this.Controls.Add(this.GroupBox5);
			this.Controls.Add(this.GroupBox4);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "DJ_frm";
			this.Text = "独立基础";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			this.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer jipAtgRsh;
	}
}
