namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcFind_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.ListBox1 = new global::System.Windows.Forms.ListBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.SuspendLayout();
			this.RadioButton1.AutoSize = true;
			this.RadioButton1.Checked = true;
			global::System.Windows.Forms.Control radioButton = this.RadioButton1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(12, 12);
			radioButton.Location = location;
			this.RadioButton1.Name = "RadioButton1";
			global::System.Windows.Forms.Control radioButton2 = this.RadioButton1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(71, 16);
			radioButton2.Size = size;
			this.RadioButton1.TabIndex = 0;
			this.RadioButton1.TabStop = true;
			this.RadioButton1.Text = "整个文档";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.RadioButton2.AutoSize = true;
			global::System.Windows.Forms.Control radioButton3 = this.RadioButton2;
			location = new global::System.Drawing.Point(78, 12);
			radioButton3.Location = location;
			this.RadioButton2.Name = "RadioButton2";
			global::System.Windows.Forms.Control radioButton4 = this.RadioButton2;
			size = new global::System.Drawing.Size(59, 16);
			radioButton4.Size = size;
			this.RadioButton2.TabIndex = 1;
			this.RadioButton2.Text = "选择集";
			this.RadioButton2.UseVisualStyleBackColor = true;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(14, 46);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(29, 12);
			label2.Size = size;
			this.Label1.TabIndex = 2;
			this.Label1.Text = "查找";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new global::System.Drawing.Point(13, 79);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(29, 12);
			label4.Size = size;
			this.Label2.TabIndex = 3;
			this.Label2.Text = "替换";
			this.TextBox1.Font = new global::System.Drawing.Font("宋体", 14f);
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(48, 39);
			textBox.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(415, 29);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 4;
			this.TextBox2.Font = new global::System.Drawing.Font("宋体", 14f);
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			location = new global::System.Drawing.Point(48, 70);
			textBox3.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new global::System.Drawing.Size(415, 29);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 5;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(15, 102);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(95, 23);
			button2.Size = size;
			this.Button1.TabIndex = 6;
			this.Button1.Text = "查找(下一个)";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(120, 102);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(58, 23);
			button4.Size = size;
			this.Button2.TabIndex = 7;
			this.Button2.Text = "替换";
			this.Button2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(184, 102);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(76, 23);
			button6.Size = size;
			this.Button3.TabIndex = 8;
			this.Button3.Text = "全部替换";
			this.Button3.UseVisualStyleBackColor = true;
			this.Label3.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new global::System.Drawing.Point(14, 270);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(449, 29);
			label6.Size = size;
			this.Label3.TabIndex = 10;
			this.Label4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label4.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label7 = this.Label4;
			location = new global::System.Drawing.Point(154, 9);
			label7.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(24, 24);
			label8.Size = size;
			this.Label4.TabIndex = 11;
			this.Label4.Text = "";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label5.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label9 = this.Label5;
			location = new global::System.Drawing.Point(179, 9);
			label9.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label10 = this.Label5;
			size = new global::System.Drawing.Size(24, 24);
			label10.Size = size;
			this.Label5.TabIndex = 12;
			this.Label5.Text = "";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label6.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label11 = this.Label6;
			location = new global::System.Drawing.Point(204, 9);
			label11.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label12 = this.Label6;
			size = new global::System.Drawing.Size(24, 24);
			label12.Size = size;
			this.Label6.TabIndex = 13;
			this.Label6.Text = "";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label7.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label7.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label13 = this.Label7;
			location = new global::System.Drawing.Point(229, 9);
			label13.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label14 = this.Label7;
			size = new global::System.Drawing.Size(24, 24);
			label14.Size = size;
			this.Label7.TabIndex = 14;
			this.Label7.Text = "";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label8.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label8.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label15 = this.Label8;
			location = new global::System.Drawing.Point(334, 9);
			label15.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label16 = this.Label8;
			size = new global::System.Drawing.Size(24, 24);
			label16.Size = size;
			this.Label8.TabIndex = 18;
			this.Label8.Text = "";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label9.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label9.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label17 = this.Label9;
			location = new global::System.Drawing.Point(309, 9);
			label17.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label18 = this.Label9;
			size = new global::System.Drawing.Size(24, 24);
			label18.Size = size;
			this.Label9.TabIndex = 17;
			this.Label9.Text = "";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label10.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label10.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label19 = this.Label10;
			location = new global::System.Drawing.Point(284, 9);
			label19.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label20 = this.Label10;
			size = new global::System.Drawing.Size(24, 24);
			label20.Size = size;
			this.Label10.TabIndex = 16;
			this.Label10.Text = "";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label11.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label11.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label21 = this.Label11;
			location = new global::System.Drawing.Point(259, 9);
			label21.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label22 = this.Label11;
			size = new global::System.Drawing.Size(24, 24);
			label22.Size = size;
			this.Label11.TabIndex = 15;
			this.Label11.Text = "";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.CheckBox1.AutoSize = true;
			global::System.Windows.Forms.Control checkBox = this.CheckBox1;
			location = new global::System.Drawing.Point(266, 106);
			checkBox.Location = location;
			this.CheckBox1.Name = "CheckBox1";
			global::System.Windows.Forms.Control checkBox2 = this.CheckBox1;
			size = new global::System.Drawing.Size(84, 16);
			checkBox2.Size = size;
			this.CheckBox1.TabIndex = 19;
			this.CheckBox1.Text = "搜索参照块";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.Label12.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label12.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label23 = this.Label12;
			location = new global::System.Drawing.Point(364, 9);
			label23.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label24 = this.Label12;
			size = new global::System.Drawing.Size(24, 24);
			label24.Size = size;
			this.Label12.TabIndex = 20;
			this.Label12.Text = "\u0082";
			this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label13.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label13.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label25 = this.Label13;
			location = new global::System.Drawing.Point(389, 9);
			label25.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label26 = this.Label13;
			size = new global::System.Drawing.Size(24, 24);
			label26.Size = size;
			this.Label13.TabIndex = 21;
			this.Label13.Text = "\u0083";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label14.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label14.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label27 = this.Label14;
			location = new global::System.Drawing.Point(414, 9);
			label27.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label28 = this.Label14;
			size = new global::System.Drawing.Size(24, 24);
			label28.Size = size;
			this.Label14.TabIndex = 22;
			this.Label14.Text = "\u0084";
			this.Label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label15.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label15.Font = new global::System.Drawing.Font("宋体", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			global::System.Windows.Forms.Control label29 = this.Label15;
			location = new global::System.Drawing.Point(439, 9);
			label29.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label30 = this.Label15;
			size = new global::System.Drawing.Size(24, 24);
			label30.Size = size;
			this.Label15.TabIndex = 23;
			this.Label15.Text = "\u0085";
			this.Label15.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.ListBox1.FormattingEnabled = true;
			this.ListBox1.ItemHeight = 12;
			global::System.Windows.Forms.Control listBox = this.ListBox1;
			location = new global::System.Drawing.Point(15, 155);
			listBox.Location = location;
			this.ListBox1.Name = "ListBox1";
			global::System.Windows.Forms.Control listBox2 = this.ListBox1;
			size = new global::System.Drawing.Size(448, 112);
			listBox2.Size = size;
			this.ListBox1.TabIndex = 24;
			this.TextBox3.Font = new global::System.Drawing.Font("宋体", 14f);
			global::System.Windows.Forms.Control textBox5 = this.TextBox3;
			location = new global::System.Drawing.Point(15, 128);
			textBox5.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox6 = this.TextBox3;
			size = new global::System.Drawing.Size(447, 29);
			textBox6.Size = size;
			this.TextBox3.TabIndex = 25;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(468, 300);
			this.ClientSize = size;
			this.Controls.Add(this.TextBox3);
			this.Controls.Add(this.ListBox1);
			this.Controls.Add(this.Label15);
			this.Controls.Add(this.Label14);
			this.Controls.Add(this.Label13);
			this.Controls.Add(this.Label12);
			this.Controls.Add(this.CheckBox1);
			this.Controls.Add(this.Label8);
			this.Controls.Add(this.Label9);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.Label11);
			this.Controls.Add(this.Label7);
			this.Controls.Add(this.Label6);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.TextBox2);
			this.Controls.Add(this.TextBox1);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.RadioButton2);
			this.Controls.Add(this.RadioButton1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "TcFind_Frm";
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
