namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcPC_frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.Button_0 = new global::System.Windows.Forms.Button();
			this.Button_1 = new global::System.Windows.Forms.Button();
			this.Button_2 = new global::System.Windows.Forms.Button();
			this.Button_3 = new global::System.Windows.Forms.Button();
			this.Button_4 = new global::System.Windows.Forms.Button();
			this.Button_5 = new global::System.Windows.Forms.Button();
			this.Button_6 = new global::System.Windows.Forms.Button();
			this.Button_7 = new global::System.Windows.Forms.Button();
			this.Button_8 = new global::System.Windows.Forms.Button();
			this.Button_9 = new global::System.Windows.Forms.Button();
			this.Button_10 = new global::System.Windows.Forms.Button();
			this.Button_11 = new global::System.Windows.Forms.Button();
			this.Button_12 = new global::System.Windows.Forms.Button();
			this.Button99 = new global::System.Windows.Forms.Button();
			this.Button98 = new global::System.Windows.Forms.Button();
			this.Button30 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.SuspendLayout();
			global::System.Windows.Forms.Control control = this.Button_0;
			global::System.Drawing.Point location = new global::System.Drawing.Point(12, 42);
			control.Location = location;
			this.Button_0.Name = "Button134";
			global::System.Windows.Forms.Control control2 = this.Button_0;
			global::System.Drawing.Size size = new global::System.Drawing.Size(112, 23);
			control2.Size = size;
			this.Button_0.TabIndex = 34;
			this.Button_0.Text = "墙板标注(砌筑)";
			this.Button_0.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control3 = this.Button_1;
			location = new global::System.Drawing.Point(13, 103);
			control3.Location = location;
			this.Button_1.Name = "Button133";
			global::System.Windows.Forms.Control control4 = this.Button_1;
			size = new global::System.Drawing.Size(110, 23);
			control4.Size = size;
			this.Button_1.TabIndex = 33;
			this.Button_1.Text = "墙板统计";
			this.Button_1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control5 = this.Button_2;
			location = new global::System.Drawing.Point(13, 16);
			control5.Location = location;
			this.Button_2.Name = "Button132";
			global::System.Windows.Forms.Control control6 = this.Button_2;
			size = new global::System.Drawing.Size(112, 23);
			control6.Size = size;
			this.Button_2.TabIndex = 32;
			this.Button_2.Text = "墙板标注(装配)";
			this.Button_2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control7 = this.Button_3;
			location = new global::System.Drawing.Point(169, 307);
			control7.Location = location;
			this.Button_3.Name = "Button109";
			global::System.Windows.Forms.Control control8 = this.Button_3;
			size = new global::System.Drawing.Size(33, 23);
			control8.Size = size;
			this.Button_3.TabIndex = 31;
			this.Button_3.Text = "LM3";
			this.Button_3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control9 = this.Button_4;
			location = new global::System.Drawing.Point(134, 307);
			control9.Location = location;
			this.Button_4.Name = "Button108";
			global::System.Windows.Forms.Control control10 = this.Button_4;
			size = new global::System.Drawing.Size(33, 23);
			control10.Size = size;
			this.Button_4.TabIndex = 30;
			this.Button_4.Text = "LM2";
			this.Button_4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control11 = this.Button_5;
			location = new global::System.Drawing.Point(170, 278);
			control11.Location = location;
			this.Button_5.Name = "Button107";
			global::System.Windows.Forms.Control control12 = this.Button_5;
			size = new global::System.Drawing.Size(32, 23);
			control12.Size = size;
			this.Button_5.TabIndex = 29;
			this.Button_5.Text = "PM3";
			this.Button_5.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control13 = this.Button_6;
			location = new global::System.Drawing.Point(136, 278);
			control13.Location = location;
			this.Button_6.Name = "Button106";
			global::System.Windows.Forms.Control control14 = this.Button_6;
			size = new global::System.Drawing.Size(32, 23);
			control14.Size = size;
			this.Button_6.TabIndex = 28;
			this.Button_6.Text = "PM2";
			this.Button_6.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control15 = this.Button_7;
			location = new global::System.Drawing.Point(101, 366);
			control15.Location = location;
			this.Button_7.Name = "Button105";
			global::System.Windows.Forms.Control control16 = this.Button_7;
			size = new global::System.Drawing.Size(87, 23);
			control16.Size = size;
			this.Button_7.TabIndex = 27;
			this.Button_7.Text = "钢筋桁架_3D";
			this.Button_7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control17 = this.Button_8;
			location = new global::System.Drawing.Point(8, 366);
			control17.Location = location;
			this.Button_8.Name = "Button104";
			global::System.Windows.Forms.Control control18 = this.Button_8;
			size = new global::System.Drawing.Size(87, 23);
			control18.Size = size;
			this.Button_8.TabIndex = 26;
			this.Button_8.Text = "钢筋桁架_2D";
			this.Button_8.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control19 = this.Button_9;
			location = new global::System.Drawing.Point(100, 337);
			control19.Location = location;
			this.Button_9.Name = "Button100";
			global::System.Windows.Forms.Control control20 = this.Button_9;
			size = new global::System.Drawing.Size(87, 23);
			control20.Size = size;
			this.Button_9.TabIndex = 25;
			this.Button_9.Text = "钢筋桁架_DM";
			this.Button_9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control21 = this.Button_10;
			location = new global::System.Drawing.Point(100, 307);
			control21.Location = location;
			this.Button_10.Name = "Button101";
			global::System.Windows.Forms.Control control22 = this.Button_10;
			size = new global::System.Drawing.Size(33, 23);
			control22.Size = size;
			this.Button_10.TabIndex = 24;
			this.Button_10.Text = "LM1";
			this.Button_10.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control23 = this.Button_11;
			location = new global::System.Drawing.Point(101, 278);
			control23.Location = location;
			this.Button_11.Name = "Button102";
			global::System.Windows.Forms.Control control24 = this.Button_11;
			size = new global::System.Drawing.Size(32, 23);
			control24.Size = size;
			this.Button_11.TabIndex = 23;
			this.Button_11.Text = "PM1";
			this.Button_11.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control control25 = this.Button_12;
			location = new global::System.Drawing.Point(14, 16);
			control25.Location = location;
			this.Button_12.Name = "Button103";
			global::System.Windows.Forms.Control control26 = this.Button_12;
			size = new global::System.Drawing.Size(74, 23);
			control26.Size = size;
			this.Button_12.TabIndex = 22;
			this.Button_12.Text = "搜索楼板";
			this.Button_12.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button = this.Button99;
			location = new global::System.Drawing.Point(8, 337);
			button.Location = location;
			this.Button99.Name = "Button99";
			global::System.Windows.Forms.Control button2 = this.Button99;
			size = new global::System.Drawing.Size(87, 23);
			button2.Size = size;
			this.Button99.TabIndex = 21;
			this.Button99.Text = "钢筋桁架_DM";
			this.Button99.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button98;
			location = new global::System.Drawing.Point(8, 307);
			button3.Location = location;
			this.Button98.Name = "Button98";
			global::System.Windows.Forms.Control button4 = this.Button98;
			size = new global::System.Drawing.Size(87, 23);
			button4.Size = size;
			this.Button98.TabIndex = 20;
			this.Button98.Text = "钢筋桁架_LM";
			this.Button98.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button5 = this.Button30;
			location = new global::System.Drawing.Point(10, 278);
			button5.Location = location;
			this.Button30.Name = "Button30";
			global::System.Windows.Forms.Control button6 = this.Button30;
			size = new global::System.Drawing.Size(87, 23);
			button6.Size = size;
			this.Button30.TabIndex = 19;
			this.Button30.Text = "钢筋桁架_PM";
			this.Button30.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button7 = this.Button1;
			location = new global::System.Drawing.Point(12, 132);
			button7.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button8 = this.Button1;
			size = new global::System.Drawing.Size(110, 23);
			button8.Size = size;
			this.Button1.TabIndex = 35;
			this.Button1.Text = "提前建筑墙体";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button9 = this.Button2;
			location = new global::System.Drawing.Point(14, 45);
			button9.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button10 = this.Button2;
			size = new global::System.Drawing.Size(142, 23);
			button10.Size = size;
			this.Button2.TabIndex = 36;
			this.Button2.Text = "叠合板拆分(双向)";
			this.Button2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button11 = this.Button3;
			location = new global::System.Drawing.Point(14, 74);
			button11.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button12 = this.Button3;
			size = new global::System.Drawing.Size(142, 23);
			button12.Size = size;
			this.Button3.TabIndex = 37;
			this.Button3.Text = "叠合板拆分(单向)";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button13 = this.Button4;
			location = new global::System.Drawing.Point(93, 16);
			button13.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button14 = this.Button4;
			size = new global::System.Drawing.Size(62, 23);
			button14.Size = size;
			this.Button4.TabIndex = 38;
			this.Button4.Text = "PL优化";
			this.Button4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button15 = this.Button5;
			location = new global::System.Drawing.Point(93, 103);
			button15.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button16 = this.Button5;
			size = new global::System.Drawing.Size(62, 23);
			button16.Size = size;
			this.Button5.TabIndex = 39;
			this.Button5.Text = "列表统计";
			this.Button5.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button17 = this.Button6;
			location = new global::System.Drawing.Point(14, 133);
			button17.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button18 = this.Button6;
			size = new global::System.Drawing.Size(97, 23);
			button18.Size = size;
			this.Button6.TabIndex = 40;
			this.Button6.Text = "Excel 2 CAD";
			this.Button6.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button19 = this.Button7;
			location = new global::System.Drawing.Point(14, 157);
			button19.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button20 = this.Button7;
			size = new global::System.Drawing.Size(97, 23);
			button20.Size = size;
			this.Button7.TabIndex = 41;
			this.Button7.Text = "CAD 2 Excel";
			this.Button7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button21 = this.Button8;
			location = new global::System.Drawing.Point(117, 157);
			button21.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button22 = this.Button8;
			size = new global::System.Drawing.Size(58, 23);
			button22.Size = size;
			this.Button8.TabIndex = 43;
			this.Button8.Text = "重量标注";
			this.Button8.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button23 = this.Button9;
			location = new global::System.Drawing.Point(117, 133);
			button23.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button24 = this.Button9;
			size = new global::System.Drawing.Size(58, 23);
			button24.Size = size;
			this.Button9.TabIndex = 42;
			this.Button9.Text = "面积标注";
			this.Button9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button25 = this.Button10;
			location = new global::System.Drawing.Point(13, 71);
			button25.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button26 = this.Button10;
			size = new global::System.Drawing.Size(112, 23);
			button26.Size = size;
			this.Button10.TabIndex = 44;
			this.Button10.Text = "装配or砌筑切换";
			this.Button10.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button27 = this.Button11;
			location = new global::System.Drawing.Point(14, 103);
			button27.Location = location;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control button28 = this.Button11;
			size = new global::System.Drawing.Size(74, 23);
			button28.Size = size;
			this.Button11.TabIndex = 45;
			this.Button11.Text = "重编号";
			this.Button11.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.Button10);
			this.GroupBox1.Controls.Add(this.Button1);
			this.GroupBox1.Controls.Add(this.Button_0);
			this.GroupBox1.Controls.Add(this.Button_1);
			this.GroupBox1.Controls.Add(this.Button_2);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new global::System.Drawing.Point(9, 2);
			groupBox.Location = location;
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(2, 2, 2, 2);
			groupBox2.Margin = padding;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox1;
			padding = new global::System.Windows.Forms.Padding(2, 2, 2, 2);
			groupBox3.Padding = padding;
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox1;
			size = new global::System.Drawing.Size(130, 193);
			groupBox4.Size = size;
			this.GroupBox1.TabIndex = 46;
			this.GroupBox1.TabStop = false;
			this.GroupBox2.Controls.Add(this.Button11);
			this.GroupBox2.Controls.Add(this.Button8);
			this.GroupBox2.Controls.Add(this.Button9);
			this.GroupBox2.Controls.Add(this.Button7);
			this.GroupBox2.Controls.Add(this.Button6);
			this.GroupBox2.Controls.Add(this.Button5);
			this.GroupBox2.Controls.Add(this.Button4);
			this.GroupBox2.Controls.Add(this.Button3);
			this.GroupBox2.Controls.Add(this.Button2);
			this.GroupBox2.Controls.Add(this.Button_12);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox2;
			location = new global::System.Drawing.Point(143, 2);
			groupBox5.Location = location;
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox2;
			padding = new global::System.Windows.Forms.Padding(2, 2, 2, 2);
			groupBox6.Margin = padding;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox2;
			padding = new global::System.Windows.Forms.Padding(2, 2, 2, 2);
			groupBox7.Padding = padding;
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox2;
			size = new global::System.Drawing.Size(187, 193);
			groupBox8.Size = size;
			this.GroupBox2.TabIndex = 47;
			this.GroupBox2.TabStop = false;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(340, 205);
			this.ClientSize = size;
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.Button_3);
			this.Controls.Add(this.Button_4);
			this.Controls.Add(this.Button_5);
			this.Controls.Add(this.Button_6);
			this.Controls.Add(this.Button_7);
			this.Controls.Add(this.Button_8);
			this.Controls.Add(this.Button_9);
			this.Controls.Add(this.Button_10);
			this.Controls.Add(this.Button_11);
			this.Controls.Add(this.Button99);
			this.Controls.Add(this.Button98);
			this.Controls.Add(this.Button30);
			this.Name = "TcPC_frm";
			this.Text = "装配设计";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
