namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcQuRa_frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.NumericUpDown1 = new global::System.Windows.Forms.NumericUpDown();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.NumericUpDown2 = new global::System.Windows.Forms.NumericUpDown();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.DataGridView1 = new global::System.Windows.Forms.DataGridView();
			this.Column1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column7 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.TextBox_2 = new global::System.Windows.Forms.TextBox();
			this.TextBox9 = new global::System.Windows.Forms.TextBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextBox8 = new global::System.Windows.Forms.TextBox();
			this.RadioButton4 = new global::System.Windows.Forms.RadioButton();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.RadioButton3 = new global::System.Windows.Forms.RadioButton();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.TextBox_0 = new global::System.Windows.Forms.TextBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.TextBox_1 = new global::System.Windows.Forms.TextBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.PrintDialog1 = new global::System.Windows.Forms.PrintDialog();
			this.Label22 = new global::System.Windows.Forms.Label();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).BeginInit();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.SuspendLayout();
			global::System.Windows.Forms.Control button = this.Button1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(47, 145);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(88, 23);
			button2.Size = size;
			this.Button1.TabIndex = 0;
			this.Button1.Text = "添加桩";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(76, 48);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(59, 20);
			button4.Size = size;
			this.Button2.TabIndex = 1;
			this.Button2.Text = "正负零";
			this.Button2.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(76, 19);
			textBox.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(59, 21);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 9;
			this.TextBox1.Text = "100";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(6, 22);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(65, 12);
			label2.Size = size;
			this.Label1.TabIndex = 10;
			this.Label1.Text = "No1:  比例";
			global::System.Windows.Forms.Control numericUpDown = this.NumericUpDown1;
			location = new global::System.Drawing.Point(59, 17);
			numericUpDown.Location = location;
			this.NumericUpDown1.Name = "NumericUpDown1";
			global::System.Windows.Forms.Control numericUpDown2 = this.NumericUpDown1;
			size = new global::System.Drawing.Size(50, 21);
			numericUpDown2.Size = size;
			this.NumericUpDown1.TabIndex = 11;
			global::System.Windows.Forms.NumericUpDown numericUpDown3 = this.NumericUpDown1;
			decimal num = new decimal(new int[]
			{
				10,
				0,
				0,
				0
			});
			numericUpDown3.Value = num;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new global::System.Drawing.Point(6, 19);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(47, 12);
			label4.Size = size;
			this.Label2.TabIndex = 12;
			this.Label2.Text = "桩长(m)";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new global::System.Drawing.Point(7, 46);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(53, 12);
			label6.Size = size;
			this.Label3.TabIndex = 14;
			this.Label3.Text = "桩径(mm)";
			global::System.Windows.Forms.NumericUpDown numericUpDown4 = this.NumericUpDown2;
			num = new decimal(new int[]
			{
				50,
				0,
				0,
				0
			});
			numericUpDown4.Increment = num;
			global::System.Windows.Forms.Control numericUpDown5 = this.NumericUpDown2;
			location = new global::System.Drawing.Point(84, 44);
			numericUpDown5.Location = location;
			global::System.Windows.Forms.NumericUpDown numericUpDown6 = this.NumericUpDown2;
			num = new decimal(new int[]
			{
				5000,
				0,
				0,
				0
			});
			numericUpDown6.Maximum = num;
			global::System.Windows.Forms.NumericUpDown numericUpDown7 = this.NumericUpDown2;
			num = new decimal(new int[]
			{
				200,
				0,
				0,
				0
			});
			numericUpDown7.Minimum = num;
			this.NumericUpDown2.Name = "NumericUpDown2";
			global::System.Windows.Forms.Control numericUpDown8 = this.NumericUpDown2;
			size = new global::System.Drawing.Size(50, 21);
			numericUpDown8.Size = size;
			this.NumericUpDown2.TabIndex = 13;
			global::System.Windows.Forms.NumericUpDown numericUpDown9 = this.NumericUpDown2;
			num = new decimal(new int[]
			{
				400,
				0,
				0,
				0
			});
			numericUpDown9.Value = num;
			global::System.Windows.Forms.Control button5 = this.Button6;
			location = new global::System.Drawing.Point(141, 144);
			button5.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button6 = this.Button6;
			size = new global::System.Drawing.Size(54, 24);
			button6.Size = size;
			this.Button6.TabIndex = 15;
			this.Button6.Text = "删除桩";
			this.Button6.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button7 = this.Button7;
			location = new global::System.Drawing.Point(47, 178);
			button7.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button8 = this.Button7;
			size = new global::System.Drawing.Size(88, 23);
			button8.Size = size;
			this.Button7.TabIndex = 16;
			this.Button7.Text = "移动桩";
			this.Button7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button9 = this.Button8;
			location = new global::System.Drawing.Point(47, 79);
			button9.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button10 = this.Button8;
			size = new global::System.Drawing.Size(88, 23);
			button10.Size = size;
			this.Button8.TabIndex = 19;
			this.Button8.Text = "添加剖面线";
			this.Button8.UseVisualStyleBackColor = true;
			this.DataGridView1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DataGridView1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column1,
				this.Column2,
				this.Column7,
				this.Column3,
				this.Column4,
				this.Column5,
				this.Column6
			});
			global::System.Windows.Forms.Control dataGridView = this.DataGridView1;
			location = new global::System.Drawing.Point(17, 180);
			dataGridView.Location = location;
			this.DataGridView1.Name = "DataGridView1";
			this.DataGridView1.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView2 = this.DataGridView1;
			size = new global::System.Drawing.Size(474, 273);
			dataGridView2.Size = size;
			this.DataGridView1.TabIndex = 20;
			this.Column1.HeaderText = "序号";
			this.Column1.Name = "Column1";
			this.Column1.Width = 40;
			this.Column2.HeaderText = "土层";
			this.Column2.Name = "Column2";
			this.Column2.Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.Column2.Width = 80;
			this.Column7.HeaderText = "厚度";
			this.Column7.Name = "Column7";
			this.Column7.Width = 40;
			this.Column3.HeaderText = "侧阻";
			this.Column3.Name = "Column3";
			this.Column3.Width = 40;
			this.Column4.HeaderText = "端阻";
			this.Column4.Name = "Column4";
			this.Column4.Width = 60;
			this.Column5.HeaderText = "液化折减";
			this.Column5.Name = "Column5";
			this.Column5.Width = 60;
			this.Column6.HeaderText = "抗拔系数";
			this.Column6.Name = "Column6";
			this.Column6.Width = 60;
			this.GroupBox1.Controls.Add(this.Label21);
			this.GroupBox1.Controls.Add(this.Label20);
			this.GroupBox1.Controls.Add(this.Button11);
			this.GroupBox1.Controls.Add(this.Label18);
			this.GroupBox1.Controls.Add(this.Label17);
			this.GroupBox1.Controls.Add(this.Label16);
			this.GroupBox1.Controls.Add(this.Label15);
			this.GroupBox1.Controls.Add(this.TextBox1);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.Button8);
			this.GroupBox1.Controls.Add(this.Button1);
			this.GroupBox1.Controls.Add(this.Button2);
			this.GroupBox1.Controls.Add(this.Button6);
			this.GroupBox1.Controls.Add(this.Button7);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new global::System.Drawing.Point(502, 7);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(205, 267);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 21;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "勘察剖面动态调整";
			this.Label21.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label21;
			location = new global::System.Drawing.Point(6, 117);
			label7.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control label8 = this.Label21;
			size = new global::System.Drawing.Size(125, 12);
			label8.Size = size;
			this.Label21.TabIndex = 27;
			this.Label21.Text = "No4:    设置土层参数";
			this.Label20.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label20;
			location = new global::System.Drawing.Point(6, 220);
			label9.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control label10 = this.Label20;
			size = new global::System.Drawing.Size(35, 12);
			label10.Size = size;
			this.Label20.TabIndex = 25;
			this.Label20.Text = "No7: ";
			global::System.Windows.Forms.Control button11 = this.Button11;
			location = new global::System.Drawing.Point(47, 215);
			button11.Location = location;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control button12 = this.Button11;
			size = new global::System.Drawing.Size(88, 23);
			button12.Size = size;
			this.Button11.TabIndex = 24;
			this.Button11.Text = "截图";
			this.Button11.UseVisualStyleBackColor = true;
			this.Label18.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label18;
			location = new global::System.Drawing.Point(6, 183);
			label11.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control label12 = this.Label18;
			size = new global::System.Drawing.Size(35, 12);
			label12.Size = size;
			this.Label18.TabIndex = 23;
			this.Label18.Text = "No6: ";
			this.Label17.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label17;
			location = new global::System.Drawing.Point(6, 152);
			label13.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control label14 = this.Label17;
			size = new global::System.Drawing.Size(35, 12);
			label14.Size = size;
			this.Label17.TabIndex = 22;
			this.Label17.Text = "No5: ";
			this.Label16.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label16;
			location = new global::System.Drawing.Point(6, 84);
			label15.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label16 = this.Label16;
			size = new global::System.Drawing.Size(35, 12);
			label16.Size = size;
			this.Label16.TabIndex = 21;
			this.Label16.Text = "No3: ";
			this.Label15.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label15;
			location = new global::System.Drawing.Point(6, 50);
			label17.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label18 = this.Label15;
			size = new global::System.Drawing.Size(65, 12);
			label18.Size = size;
			this.Label15.TabIndex = 20;
			this.Label15.Text = "No2:  标高";
			this.RadioButton1.AutoSize = true;
			this.RadioButton1.Checked = true;
			global::System.Windows.Forms.Control radioButton = this.RadioButton1;
			location = new global::System.Drawing.Point(9, 20);
			radioButton.Location = location;
			this.RadioButton1.Name = "RadioButton1";
			global::System.Windows.Forms.Control radioButton2 = this.RadioButton1;
			size = new global::System.Drawing.Size(47, 16);
			radioButton2.Size = size;
			this.RadioButton1.TabIndex = 22;
			this.RadioButton1.TabStop = true;
			this.RadioButton1.Text = "方桩";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.RadioButton2.AutoSize = true;
			global::System.Windows.Forms.Control radioButton3 = this.RadioButton2;
			location = new global::System.Drawing.Point(84, 20);
			radioButton3.Location = location;
			this.RadioButton2.Name = "RadioButton2";
			global::System.Windows.Forms.Control radioButton4 = this.RadioButton2;
			size = new global::System.Drawing.Size(47, 16);
			radioButton4.Size = size;
			this.RadioButton2.TabIndex = 23;
			this.RadioButton2.TabStop = true;
			this.RadioButton2.Text = "圆桩";
			this.RadioButton2.UseVisualStyleBackColor = true;
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label19 = this.Label5;
			location = new global::System.Drawing.Point(143, 48);
			label19.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label20 = this.Label5;
			size = new global::System.Drawing.Size(53, 12);
			label20.Size = size;
			this.Label5.TabIndex = 25;
			this.Label5.Text = "内径(mm)";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label21 = this.Label6;
			location = new global::System.Drawing.Point(9, 73);
			label21.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label22 = this.Label6;
			size = new global::System.Drawing.Size(47, 12);
			label22.Size = size;
			this.Label6.TabIndex = 26;
			this.Label6.Text = "周长(m)";
			global::System.Windows.Forms.Control textBox3 = this.TextBox3;
			location = new global::System.Drawing.Point(84, 70);
			textBox3.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox4 = this.TextBox3;
			size = new global::System.Drawing.Size(50, 21);
			textBox4.Size = size;
			this.TextBox3.TabIndex = 27;
			this.TextBox3.Text = "0";
			global::System.Windows.Forms.Control textBox5 = this.TextBox4;
			location = new global::System.Drawing.Point(84, 93);
			textBox5.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox6 = this.TextBox4;
			size = new global::System.Drawing.Size(50, 21);
			textBox6.Size = size;
			this.TextBox4.TabIndex = 29;
			this.TextBox4.Text = "0";
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label23 = this.Label7;
			location = new global::System.Drawing.Point(9, 96);
			label23.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label24 = this.Label7;
			size = new global::System.Drawing.Size(65, 12);
			label24.Size = size;
			this.Label7.TabIndex = 28;
			this.Label7.Text = "面积Ap(m²)";
			global::System.Windows.Forms.Control textBox7 = this.TextBox5;
			location = new global::System.Drawing.Point(220, 93);
			textBox7.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox8 = this.TextBox5;
			size = new global::System.Drawing.Size(50, 21);
			textBox8.Size = size;
			this.TextBox5.TabIndex = 31;
			this.TextBox5.Text = "0";
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label25 = this.Label8;
			location = new global::System.Drawing.Point(143, 96);
			label25.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label26 = this.Label8;
			size = new global::System.Drawing.Size(71, 12);
			label26.Size = size;
			this.Label8.TabIndex = 30;
			this.Label8.Text = "面积Ap1(m²)";
			this.GroupBox2.Controls.Add(this.TextBox2);
			this.GroupBox2.Controls.Add(this.TextBox5);
			this.GroupBox2.Controls.Add(this.Label8);
			this.GroupBox2.Controls.Add(this.TextBox4);
			this.GroupBox2.Controls.Add(this.Label7);
			this.GroupBox2.Controls.Add(this.TextBox3);
			this.GroupBox2.Controls.Add(this.Label6);
			this.GroupBox2.Controls.Add(this.Label5);
			this.GroupBox2.Controls.Add(this.RadioButton2);
			this.GroupBox2.Controls.Add(this.RadioButton1);
			this.GroupBox2.Controls.Add(this.Label3);
			this.GroupBox2.Controls.Add(this.NumericUpDown2);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			location = new global::System.Drawing.Point(17, 7);
			groupBox3.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(278, 139);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 32;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "截面参数";
			global::System.Windows.Forms.Control textBox9 = this.TextBox2;
			location = new global::System.Drawing.Point(220, 43);
			textBox9.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox10 = this.TextBox2;
			size = new global::System.Drawing.Size(50, 21);
			textBox10.Size = size;
			this.TextBox2.TabIndex = 32;
			this.TextBox2.Text = "0";
			this.GroupBox3.Controls.Add(this.TextBox_2);
			this.GroupBox3.Controls.Add(this.TextBox9);
			this.GroupBox3.Controls.Add(this.Label19);
			this.GroupBox3.Controls.Add(this.Label12);
			this.GroupBox3.Controls.Add(this.TextBox8);
			this.GroupBox3.Controls.Add(this.RadioButton4);
			this.GroupBox3.Controls.Add(this.Label11);
			this.GroupBox3.Controls.Add(this.RadioButton3);
			this.GroupBox3.Controls.Add(this.TextBox7);
			this.GroupBox3.Controls.Add(this.Label10);
			this.GroupBox3.Controls.Add(this.TextBox6);
			this.GroupBox3.Controls.Add(this.Label9);
			this.GroupBox3.Controls.Add(this.Label2);
			this.GroupBox3.Controls.Add(this.NumericUpDown1);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox3;
			location = new global::System.Drawing.Point(301, 8);
			groupBox5.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox3;
			size = new global::System.Drawing.Size(189, 138);
			groupBox6.Size = size;
			this.GroupBox3.TabIndex = 33;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "竖向参数";
			global::System.Windows.Forms.Control control = this.TextBox_2;
			location = new global::System.Drawing.Point(59, 62);
			control.Location = location;
			this.TextBox_2.Name = "TextBox12";
			global::System.Windows.Forms.Control control2 = this.TextBox_2;
			size = new global::System.Drawing.Size(50, 21);
			control2.Size = size;
			this.TextBox_2.TabIndex = 41;
			this.TextBox_2.Text = "0.000";
			this.TextBox_2.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.Control textBox11 = this.TextBox9;
			location = new global::System.Drawing.Point(162, 107);
			textBox11.Location = location;
			this.TextBox9.Name = "TextBox9";
			global::System.Windows.Forms.Control textBox12 = this.TextBox9;
			size = new global::System.Drawing.Size(21, 21);
			textBox12.Size = size;
			this.TextBox9.TabIndex = 38;
			this.TextBox9.Text = "0";
			this.TextBox9.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label19.AutoSize = true;
			global::System.Windows.Forms.Control label27 = this.Label19;
			location = new global::System.Drawing.Point(6, 66);
			label27.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control label28 = this.Label19;
			size = new global::System.Drawing.Size(53, 12);
			label28.Size = size;
			this.Label19.TabIndex = 40;
			this.Label19.Text = "场地标高";
			this.Label12.AutoSize = true;
			global::System.Windows.Forms.Control label29 = this.Label12;
			location = new global::System.Drawing.Point(115, 111);
			label29.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label30 = this.Label12;
			size = new global::System.Drawing.Size(41, 12);
			label30.Size = size;
			this.Label12.TabIndex = 37;
			this.Label12.Text = "持力层";
			global::System.Windows.Forms.Control textBox13 = this.TextBox8;
			location = new global::System.Drawing.Point(59, 107);
			textBox13.Location = location;
			this.TextBox8.Name = "TextBox8";
			global::System.Windows.Forms.Control textBox14 = this.TextBox8;
			size = new global::System.Drawing.Size(50, 21);
			textBox14.Size = size;
			this.TextBox8.TabIndex = 36;
			this.TextBox8.Text = "0.000";
			this.TextBox8.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.RadioButton4.AutoSize = true;
			global::System.Windows.Forms.Control radioButton5 = this.RadioButton4;
			location = new global::System.Drawing.Point(117, 69);
			radioButton5.Location = location;
			this.RadioButton4.Name = "RadioButton4";
			global::System.Windows.Forms.Control radioButton6 = this.RadioButton4;
			size = new global::System.Drawing.Size(47, 16);
			radioButton6.Size = size;
			this.RadioButton4.TabIndex = 38;
			this.RadioButton4.Text = "抗拔";
			this.RadioButton4.UseVisualStyleBackColor = true;
			this.Label11.AutoSize = true;
			global::System.Windows.Forms.Control label31 = this.Label11;
			location = new global::System.Drawing.Point(6, 111);
			label31.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label32 = this.Label11;
			size = new global::System.Drawing.Size(41, 12);
			label32.Size = size;
			this.Label11.TabIndex = 35;
			this.Label11.Text = "底标高";
			this.RadioButton3.AutoSize = true;
			this.RadioButton3.Checked = true;
			global::System.Windows.Forms.Control radioButton7 = this.RadioButton3;
			location = new global::System.Drawing.Point(115, 20);
			radioButton7.Location = location;
			this.RadioButton3.Name = "RadioButton3";
			global::System.Windows.Forms.Control radioButton8 = this.RadioButton3;
			size = new global::System.Drawing.Size(47, 16);
			radioButton8.Size = size;
			this.RadioButton3.TabIndex = 37;
			this.RadioButton3.TabStop = true;
			this.RadioButton3.Text = "抗压";
			this.RadioButton3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox15 = this.TextBox7;
			location = new global::System.Drawing.Point(59, 85);
			textBox15.Location = location;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox16 = this.TextBox7;
			size = new global::System.Drawing.Size(50, 21);
			textBox16.Size = size;
			this.TextBox7.TabIndex = 34;
			this.TextBox7.Text = "0.000";
			this.TextBox7.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label10.AutoSize = true;
			global::System.Windows.Forms.Control label33 = this.Label10;
			location = new global::System.Drawing.Point(6, 89);
			label33.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label34 = this.Label10;
			size = new global::System.Drawing.Size(41, 12);
			label34.Size = size;
			this.Label10.TabIndex = 33;
			this.Label10.Text = "顶标高";
			global::System.Windows.Forms.Control textBox17 = this.TextBox6;
			location = new global::System.Drawing.Point(59, 38);
			textBox17.Location = location;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox18 = this.TextBox6;
			size = new global::System.Drawing.Size(50, 21);
			textBox18.Size = size;
			this.TextBox6.TabIndex = 32;
			this.TextBox6.Text = "0";
			this.TextBox6.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label35 = this.Label9;
			location = new global::System.Drawing.Point(6, 41);
			label35.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label36 = this.Label9;
			size = new global::System.Drawing.Size(47, 12);
			label36.Size = size;
			this.Label9.TabIndex = 14;
			this.Label9.Text = "入土(m)";
			global::System.Windows.Forms.Control button13 = this.Button10;
			location = new global::System.Drawing.Point(478, 150);
			button13.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button14 = this.Button10;
			size = new global::System.Drawing.Size(12, 24);
			button14.Size = size;
			this.Button10.TabIndex = 39;
			this.Button10.Text = ">";
			this.Button10.UseVisualStyleBackColor = true;
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label37 = this.Label4;
			location = new global::System.Drawing.Point(20, 159);
			label37.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label38 = this.Label4;
			size = new global::System.Drawing.Size(53, 12);
			label38.Size = size;
			this.Label4.TabIndex = 34;
			this.Label4.Text = "土层参数";
			global::System.Windows.Forms.Control button15 = this.Button3;
			location = new global::System.Drawing.Point(417, 150);
			button15.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button16 = this.Button3;
			size = new global::System.Drawing.Size(49, 25);
			button16.Size = size;
			this.Button3.TabIndex = 35;
			this.Button3.Text = "-";
			this.Button3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button17 = this.Button4;
			location = new global::System.Drawing.Point(361, 151);
			button17.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button18 = this.Button4;
			size = new global::System.Drawing.Size(49, 25);
			button18.Size = size;
			this.Button4.TabIndex = 36;
			this.Button4.Text = "+";
			this.Button4.UseVisualStyleBackColor = true;
			this.TextBox_0.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control control3 = this.TextBox_0;
			location = new global::System.Drawing.Point(213, 476);
			control3.Location = location;
			this.TextBox_0.Name = "TextBox10";
			global::System.Windows.Forms.Control control4 = this.TextBox_0;
			size = new global::System.Drawing.Size(50, 21);
			control4.Size = size;
			this.TextBox_0.TabIndex = 40;
			this.TextBox_0.Text = "0";
			this.TextBox_0.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label13.AutoSize = true;
			global::System.Windows.Forms.Control label39 = this.Label13;
			location = new global::System.Drawing.Point(15, 482);
			label39.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label40 = this.Label13;
			size = new global::System.Drawing.Size(161, 12);
			label40.Size = size;
			this.Label13.TabIndex = 39;
			this.Label13.Text = "单桩极限承载力标准值Qu(KN)";
			this.TextBox_1.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control control5 = this.TextBox_1;
			location = new global::System.Drawing.Point(213, 502);
			control5.Location = location;
			this.TextBox_1.Name = "TextBox11";
			global::System.Windows.Forms.Control control6 = this.TextBox_1;
			size = new global::System.Drawing.Size(50, 21);
			control6.Size = size;
			this.TextBox_1.TabIndex = 42;
			this.TextBox_1.Text = "0";
			this.TextBox_1.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label14.AutoSize = true;
			global::System.Windows.Forms.Control label41 = this.Label14;
			location = new global::System.Drawing.Point(15, 506);
			label41.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label42 = this.Label14;
			size = new global::System.Drawing.Size(161, 12);
			label42.Size = size;
			this.Label14.TabIndex = 41;
			this.Label14.Text = "单桩极限承载力特征值Ra(KN)";
			global::System.Windows.Forms.Control button19 = this.Button5;
			location = new global::System.Drawing.Point(408, 472);
			button19.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button20 = this.Button5;
			size = new global::System.Drawing.Size(57, 25);
			button20.Size = size;
			this.Button5.TabIndex = 43;
			this.Button5.Text = "计算";
			this.Button5.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button21 = this.Button9;
			location = new global::System.Drawing.Point(330, 472);
			button21.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button22 = this.Button9;
			size = new global::System.Drawing.Size(49, 25);
			button22.Size = size;
			this.Button9.TabIndex = 44;
			this.Button9.Text = "帮助";
			this.Button9.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control pictureBox = this.PictureBox1;
			location = new global::System.Drawing.Point(502, 284);
			pictureBox.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox1;
			size = new global::System.Drawing.Size(204, 239);
			pictureBox2.Size = size;
			this.PictureBox1.TabIndex = 45;
			this.PictureBox1.TabStop = false;
			global::System.Windows.Forms.Control button23 = this.Button12;
			location = new global::System.Drawing.Point(408, 498);
			button23.Location = location;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button24 = this.Button12;
			size = new global::System.Drawing.Size(57, 25);
			button24.Size = size;
			this.Button12.TabIndex = 46;
			this.Button12.Text = "计算书";
			this.Button12.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button25 = this.Button13;
			location = new global::System.Drawing.Point(330, 498);
			button25.Location = location;
			this.Button13.Name = "Button13";
			global::System.Windows.Forms.Control button26 = this.Button13;
			size = new global::System.Drawing.Size(49, 25);
			button26.Size = size;
			this.Button13.TabIndex = 47;
			this.Button13.Text = "打印";
			this.Button13.UseVisualStyleBackColor = true;
			this.PrintDialog1.UseEXDialog = true;
			this.Label22.AutoSize = true;
			global::System.Windows.Forms.Control label43 = this.Label22;
			location = new global::System.Drawing.Point(15, 458);
			label43.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control label44 = this.Label22;
			size = new global::System.Drawing.Size(0, 12);
			label44.Size = size;
			this.Label22.TabIndex = 48;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(708, 536);
			this.ClientSize = size;
			this.Controls.Add(this.Label22);
			this.Controls.Add(this.Button13);
			this.Controls.Add(this.Button12);
			this.Controls.Add(this.PictureBox1);
			this.Controls.Add(this.Button9);
			this.Controls.Add(this.Button10);
			this.Controls.Add(this.Button5);
			this.Controls.Add(this.TextBox_1);
			this.Controls.Add(this.Label14);
			this.Controls.Add(this.TextBox_0);
			this.Controls.Add(this.Label13);
			this.Controls.Add(this.Button4);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.DataGridView1);
			this.Name = "TcQuRa_frm";
			this.Text = "单桩竖向极限承载力";
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
