namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcXG_frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.DataGridView1 = new global::System.Windows.Forms.DataGridView();
			this.TabPage6 = new global::System.Windows.Forms.TabPage();
			this.DataGridView2 = new global::System.Windows.Forms.DataGridView();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.DataGridView3 = new global::System.Windows.Forms.DataGridView();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.DataGridView4 = new global::System.Windows.Forms.DataGridView();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.DataGridView5 = new global::System.Windows.Forms.DataGridView();
			this.TabPage5 = new global::System.Windows.Forms.TabPage();
			this.DataGridView6 = new global::System.Windows.Forms.DataGridView();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).BeginInit();
			this.TabPage6.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).BeginInit();
			this.TabPage2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView3).BeginInit();
			this.TabPage3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView4).BeginInit();
			this.TabPage4.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView5).BeginInit();
			this.TabPage5.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView6).BeginInit();
			this.SuspendLayout();
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage6);
			this.TabControl1.Controls.Add(this.TabPage2);
			this.TabControl1.Controls.Add(this.TabPage3);
			this.TabControl1.Controls.Add(this.TabPage4);
			this.TabControl1.Controls.Add(this.TabPage5);
			global::System.Windows.Forms.Control tabControl = this.TabControl1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(1, 0);
			tabControl.Location = location;
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl2 = this.TabControl1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(381, 188);
			tabControl2.Size = size;
			this.TabControl1.TabIndex = 0;
			this.TabPage1.Controls.Add(this.DataGridView1);
			global::System.Windows.Forms.TabPage tabPage = this.TabPage1;
			location = new global::System.Drawing.Point(4, 21);
			tabPage.Location = location;
			this.TabPage1.Name = "TabPage1";
			global::System.Windows.Forms.Control tabPage2 = this.TabPage1;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			tabPage2.Padding = padding;
			global::System.Windows.Forms.Control tabPage3 = this.TabPage1;
			size = new global::System.Drawing.Size(373, 163);
			tabPage3.Size = size;
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "等边角钢";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.DataGridView1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			global::System.Windows.Forms.Control dataGridView = this.DataGridView1;
			location = new global::System.Drawing.Point(6, 6);
			dataGridView.Location = location;
			this.DataGridView1.Name = "DataGridView1";
			this.DataGridView1.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView2 = this.DataGridView1;
			size = new global::System.Drawing.Size(361, 151);
			dataGridView2.Size = size;
			this.DataGridView1.TabIndex = 1;
			this.TabPage6.Controls.Add(this.DataGridView2);
			global::System.Windows.Forms.TabPage tabPage4 = this.TabPage6;
			location = new global::System.Drawing.Point(4, 21);
			tabPage4.Location = location;
			this.TabPage6.Name = "TabPage6";
			global::System.Windows.Forms.Control tabPage5 = this.TabPage6;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage5.Padding = padding;
			global::System.Windows.Forms.Control tabPage6 = this.TabPage6;
			size = new global::System.Drawing.Size(373, 163);
			tabPage6.Size = size;
			this.TabPage6.TabIndex = 5;
			this.TabPage6.Text = "不等边角钢";
			this.TabPage6.UseVisualStyleBackColor = true;
			this.DataGridView2.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			global::System.Windows.Forms.Control dataGridView3 = this.DataGridView2;
			location = new global::System.Drawing.Point(6, 6);
			dataGridView3.Location = location;
			this.DataGridView2.Name = "DataGridView2";
			this.DataGridView2.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView4 = this.DataGridView2;
			size = new global::System.Drawing.Size(361, 151);
			dataGridView4.Size = size;
			this.DataGridView2.TabIndex = 2;
			this.TabPage2.Controls.Add(this.DataGridView3);
			global::System.Windows.Forms.TabPage tabPage7 = this.TabPage2;
			location = new global::System.Drawing.Point(4, 21);
			tabPage7.Location = location;
			this.TabPage2.Name = "TabPage2";
			global::System.Windows.Forms.Control tabPage8 = this.TabPage2;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage8.Padding = padding;
			global::System.Windows.Forms.Control tabPage9 = this.TabPage2;
			size = new global::System.Drawing.Size(373, 163);
			tabPage9.Size = size;
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "工字钢";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.DataGridView3.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			global::System.Windows.Forms.Control dataGridView5 = this.DataGridView3;
			location = new global::System.Drawing.Point(6, 6);
			dataGridView5.Location = location;
			this.DataGridView3.Name = "DataGridView3";
			this.DataGridView3.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView6 = this.DataGridView3;
			size = new global::System.Drawing.Size(361, 151);
			dataGridView6.Size = size;
			this.DataGridView3.TabIndex = 2;
			this.TabPage3.Controls.Add(this.DataGridView4);
			global::System.Windows.Forms.TabPage tabPage10 = this.TabPage3;
			location = new global::System.Drawing.Point(4, 21);
			tabPage10.Location = location;
			this.TabPage3.Name = "TabPage3";
			global::System.Windows.Forms.Control tabPage11 = this.TabPage3;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage11.Padding = padding;
			global::System.Windows.Forms.Control tabPage12 = this.TabPage3;
			size = new global::System.Drawing.Size(373, 163);
			tabPage12.Size = size;
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "H型钢";
			this.TabPage3.UseVisualStyleBackColor = true;
			this.DataGridView4.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			global::System.Windows.Forms.Control dataGridView7 = this.DataGridView4;
			location = new global::System.Drawing.Point(6, 6);
			dataGridView7.Location = location;
			this.DataGridView4.Name = "DataGridView4";
			this.DataGridView4.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView8 = this.DataGridView4;
			size = new global::System.Drawing.Size(361, 151);
			dataGridView8.Size = size;
			this.DataGridView4.TabIndex = 2;
			this.TabPage4.Controls.Add(this.DataGridView5);
			global::System.Windows.Forms.TabPage tabPage13 = this.TabPage4;
			location = new global::System.Drawing.Point(4, 21);
			tabPage13.Location = location;
			this.TabPage4.Name = "TabPage4";
			global::System.Windows.Forms.Control tabPage14 = this.TabPage4;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage14.Padding = padding;
			global::System.Windows.Forms.Control tabPage15 = this.TabPage4;
			size = new global::System.Drawing.Size(373, 163);
			tabPage15.Size = size;
			this.TabPage4.TabIndex = 3;
			this.TabPage4.Text = "槽钢";
			this.TabPage4.UseVisualStyleBackColor = true;
			this.DataGridView5.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			global::System.Windows.Forms.Control dataGridView9 = this.DataGridView5;
			location = new global::System.Drawing.Point(6, 6);
			dataGridView9.Location = location;
			this.DataGridView5.Name = "DataGridView5";
			this.DataGridView5.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView10 = this.DataGridView5;
			size = new global::System.Drawing.Size(361, 151);
			dataGridView10.Size = size;
			this.DataGridView5.TabIndex = 2;
			this.TabPage5.Controls.Add(this.DataGridView6);
			global::System.Windows.Forms.TabPage tabPage16 = this.TabPage5;
			location = new global::System.Drawing.Point(4, 21);
			tabPage16.Location = location;
			this.TabPage5.Name = "TabPage5";
			global::System.Windows.Forms.Control tabPage17 = this.TabPage5;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage17.Padding = padding;
			global::System.Windows.Forms.Control tabPage18 = this.TabPage5;
			size = new global::System.Drawing.Size(373, 163);
			tabPage18.Size = size;
			this.TabPage5.TabIndex = 4;
			this.TabPage5.Text = "C型钢";
			this.TabPage5.UseVisualStyleBackColor = true;
			this.DataGridView6.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			global::System.Windows.Forms.Control dataGridView11 = this.DataGridView6;
			location = new global::System.Drawing.Point(6, 6);
			dataGridView11.Location = location;
			this.DataGridView6.Name = "DataGridView6";
			this.DataGridView6.RowTemplate.Height = 23;
			global::System.Windows.Forms.Control dataGridView12 = this.DataGridView6;
			size = new global::System.Drawing.Size(361, 151);
			dataGridView12.Size = size;
			this.DataGridView6.TabIndex = 2;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(382, 184);
			this.ClientSize = size;
			this.Controls.Add(this.TabControl1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			this.Name = "XG_frm";
			this.Text = "型钢绘制";
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView1).EndInit();
			this.TabPage6.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView2).EndInit();
			this.TabPage2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView3).EndInit();
			this.TabPage3.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView4).EndInit();
			this.TabPage4.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView5).EndInit();
			this.TabPage5.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DataGridView6).EndInit();
			this.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
