namespace 田草CAD工具箱_For2014
{
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TcZJM_Frm : global::System.Windows.Forms.Form
	{
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.ListBox1 = new global::System.Windows.Forms.ListBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.GroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.SuspendLayout();
			this.TextBox1.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox1.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			this.TextBox1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(47, 74);
			textBox.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(100, 21);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 2;
			this.TextBox2.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox2.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			this.TextBox2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control textBox3 = this.TextBox2;
			location = new global::System.Drawing.Point(47, 97);
			textBox3.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new global::System.Drawing.Size(100, 21);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 3;
			this.TextBox3.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox3.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			this.TextBox3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control textBox5 = this.TextBox3;
			location = new global::System.Drawing.Point(47, 120);
			textBox5.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox6 = this.TextBox3;
			size = new global::System.Drawing.Size(100, 21);
			textBox6.Size = size;
			this.TextBox3.TabIndex = 4;
			this.TextBox4.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox4.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			this.TextBox4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control textBox7 = this.TextBox4;
			location = new global::System.Drawing.Point(47, 143);
			textBox7.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox8 = this.TextBox4;
			size = new global::System.Drawing.Size(100, 21);
			textBox8.Size = size;
			this.TextBox4.TabIndex = 5;
			this.TextBox5.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox5.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			this.TextBox5.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control textBox9 = this.TextBox5;
			location = new global::System.Drawing.Point(47, 166);
			textBox9.Location = location;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control textBox10 = this.TextBox5;
			size = new global::System.Drawing.Size(100, 21);
			textBox10.Size = size;
			this.TextBox5.TabIndex = 6;
			this.TextBox6.BackColor = global::System.Drawing.SystemColors.Window;
			this.TextBox6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox6.Font = new global::System.Drawing.Font("宋体", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 134);
			this.TextBox6.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control textBox11 = this.TextBox6;
			location = new global::System.Drawing.Point(47, 189);
			textBox11.Location = location;
			this.TextBox6.Multiline = true;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox12 = this.TextBox6;
			size = new global::System.Drawing.Size(100, 21);
			textBox12.Size = size;
			this.TextBox6.TabIndex = 7;
			this.Button1.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(47, 220);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(99, 22);
			button2.Size = size;
			this.Button1.TabIndex = 8;
			this.Button1.Text = "确定";
			this.Button1.UseVisualStyleBackColor = true;
			this.RadioButton1.AutoSize = true;
			this.RadioButton1.Checked = true;
			this.RadioButton1.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control radioButton = this.RadioButton1;
			location = new global::System.Drawing.Point(46, 20);
			radioButton.Location = location;
			this.RadioButton1.Name = "RadioButton1";
			global::System.Windows.Forms.Control radioButton2 = this.RadioButton1;
			size = new global::System.Drawing.Size(47, 16);
			radioButton2.Size = size;
			this.RadioButton1.TabIndex = 9;
			this.RadioButton1.TabStop = true;
			this.RadioButton1.Text = "方柱";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.RadioButton2.AutoSize = true;
			this.RadioButton2.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control radioButton3 = this.RadioButton2;
			location = new global::System.Drawing.Point(99, 20);
			radioButton3.Location = location;
			this.RadioButton2.Name = "RadioButton2";
			global::System.Windows.Forms.Control radioButton4 = this.RadioButton2;
			size = new global::System.Drawing.Size(47, 16);
			radioButton4.Size = size;
			this.RadioButton2.TabIndex = 10;
			this.RadioButton2.Text = "圆柱";
			this.RadioButton2.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.Label7);
			this.GroupBox1.Controls.Add(this.ComboBox1);
			this.GroupBox1.Controls.Add(this.Label6);
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.RadioButton2);
			this.GroupBox1.Controls.Add(this.RadioButton1);
			this.GroupBox1.Controls.Add(this.Button1);
			this.GroupBox1.Controls.Add(this.TextBox6);
			this.GroupBox1.Controls.Add(this.TextBox5);
			this.GroupBox1.Controls.Add(this.TextBox4);
			this.GroupBox1.Controls.Add(this.TextBox3);
			this.GroupBox1.Controls.Add(this.TextBox2);
			this.GroupBox1.Controls.Add(this.TextBox1);
			this.GroupBox1.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new global::System.Drawing.Point(2, 3);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(160, 248);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 11;
			this.GroupBox1.TabStop = false;
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label7;
			location = new global::System.Drawing.Point(10, 51);
			label.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label2 = this.Label7;
			size = new global::System.Drawing.Size(29, 12);
			label2.Size = size;
			this.Label7.TabIndex = 17;
			this.Label7.Text = "比例";
			this.ComboBox1.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox = this.ComboBox1;
			location = new global::System.Drawing.Point(46, 48);
			comboBox.Location = location;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox1;
			size = new global::System.Drawing.Size(100, 20);
			comboBox2.Size = size;
			this.ComboBox1.TabIndex = 12;
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label6;
			location = new global::System.Drawing.Point(12, 147);
			label3.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label4 = this.Label6;
			size = new global::System.Drawing.Size(29, 12);
			label4.Size = size;
			this.Label6.TabIndex = 16;
			this.Label6.Text = "箍筋";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label5;
			location = new global::System.Drawing.Point(6, 193);
			label5.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label6 = this.Label5;
			size = new global::System.Drawing.Size(35, 12);
			label6.Size = size;
			this.Label5.TabIndex = 15;
			this.Label5.Text = "纵筋Y";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label4;
			location = new global::System.Drawing.Point(6, 170);
			label7.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(35, 12);
			label8.Size = size;
			this.Label4.TabIndex = 14;
			this.Label4.Text = "纵筋X";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label3;
			location = new global::System.Drawing.Point(12, 124);
			label9.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label10 = this.Label3;
			size = new global::System.Drawing.Size(29, 12);
			label10.Size = size;
			this.Label3.TabIndex = 13;
			this.Label3.Text = "纵筋";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label2;
			location = new global::System.Drawing.Point(12, 101);
			label11.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label12 = this.Label2;
			size = new global::System.Drawing.Size(29, 12);
			label12.Size = size;
			this.Label2.TabIndex = 12;
			this.Label2.Text = "截面";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label1;
			location = new global::System.Drawing.Point(12, 78);
			label13.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label14 = this.Label1;
			size = new global::System.Drawing.Size(29, 12);
			label14.Size = size;
			this.Label1.TabIndex = 11;
			this.Label1.Text = "名称";
			this.PictureBox1.BackColor = global::System.Drawing.Color.DimGray;
			global::System.Windows.Forms.Control pictureBox = this.PictureBox1;
			location = new global::System.Drawing.Point(168, 10);
			pictureBox.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox1;
			size = new global::System.Drawing.Size(229, 95);
			pictureBox2.Size = size;
			this.PictureBox1.TabIndex = 21;
			this.PictureBox1.TabStop = false;
			this.ListBox1.FormattingEnabled = true;
			this.ListBox1.ItemHeight = 12;
			global::System.Windows.Forms.Control listBox = this.ListBox1;
			location = new global::System.Drawing.Point(168, 113);
			listBox.Location = location;
			this.ListBox1.Name = "ListBox1";
			global::System.Windows.Forms.Control listBox2 = this.ListBox1;
			size = new global::System.Drawing.Size(229, 136);
			listBox2.Size = size;
			this.ListBox1.TabIndex = 12;
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.DimGray;
			this.Label11.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label15 = this.Label11;
			location = new global::System.Drawing.Point(298, 72);
			label15.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label16 = this.Label11;
			size = new global::System.Drawing.Size(47, 12);
			label16.Size = size;
			this.Label11.TabIndex = 26;
			this.Label11.Text = "Label11";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.DimGray;
			this.Label10.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label17 = this.Label10;
			location = new global::System.Drawing.Point(289, 10);
			label17.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label18 = this.Label10;
			size = new global::System.Drawing.Size(47, 12);
			label18.Size = size;
			this.Label10.TabIndex = 25;
			this.Label10.Text = "Label10";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel1.BackColor = global::System.Drawing.Color.DimGray;
			global::System.Windows.Forms.Control panel = this.Panel1;
			location = new global::System.Drawing.Point(217, 29);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(16, 37);
			panel2.Size = size;
			this.Panel1.TabIndex = 24;
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.DimGray;
			this.Label8.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label19 = this.Label8;
			location = new global::System.Drawing.Point(247, 72);
			label19.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label20 = this.Label8;
			size = new global::System.Drawing.Size(41, 12);
			label20.Size = size;
			this.Label8.TabIndex = 22;
			this.Label8.Text = "Label8";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label12.BackColor = global::System.Drawing.Color.DimGray;
			this.Label12.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control label21 = this.Label12;
			location = new global::System.Drawing.Point(249, 29);
			label21.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label22 = this.Label12;
			size = new global::System.Drawing.Size(45, 34);
			label22.Size = size;
			this.Label12.TabIndex = 27;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.Control;
			size = new global::System.Drawing.Size(409, 258);
			this.ClientSize = size;
			this.Controls.Add(this.Label12);
			this.Controls.Add(this.Label11);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.Label8);
			this.Controls.Add(this.PictureBox1);
			this.Controls.Add(this.ListBox1);
			this.Controls.Add(this.GroupBox1);
			this.ForeColor = global::System.Drawing.Color.White;
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "TcZJM_Frm";
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "柱截面绘制";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
