using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Autodesk.AutoCAD.Runtime;
using TerrainComputeC;
using TerrainComputeC.BASE;
using TerrainComputeC.HULL;
using TerrainComputeC.IO;

[assembly: AssemblyVersion("0.0.0.1")]
[assembly: CommandClass(typeof(CMD_Colorize))]
[assembly: CommandClass(typeof(Triangulate))]
[assembly: CommandClass(typeof(EntitySlicer))]
[assembly: CommandClass(typeof(CMD_MinAreaEnclosingRectangle))]
[assembly: CommandClass(typeof(OFF))]
[assembly: CommandClass(typeof(MenuLoader))]
[assembly: CommandClass(typeof(PointGeneration))]
[assembly: CommandClass(typeof(CMD_QSelectFaces))]
[assembly: CommandClass(typeof(IO2))]
[assembly: CommandClass(typeof(ContourLineComputation))]
[assembly: CommandClass(typeof(CMD_FacesToMesh))]
[assembly: CommandClass(typeof(TerrainComputeC.My.UserCmd))]
[assembly: CommandClass(typeof(Tesselation))]
[assembly: CommandClass(typeof(PointBlurring))]
[assembly: CommandClass(typeof(CMD_Development))]
[assembly: CommandClass(typeof(CMD_MinimumEnclosingCircle))]
[assembly: CommandClass(typeof(PointProjection))]
[assembly: CommandClass(typeof(CMD_Silhouette))]
[assembly: CommandClass(typeof(CMD_STL))]
[assembly: CommandClass(typeof(CMD_ReconstructSurface))]
[assembly: CommandClass(typeof(CMD_Hull3d))]
[assembly: CommandClass(typeof(CMD_Hull2d))]
[assembly: CommandClass(typeof(PLine))]
[assembly: CommandClass(typeof(CMD_FacesToSolid))]
//[assembly: CommandClass(typeof(AboutObject))]
[assembly: CommandClass(typeof(LineProjection))]
[assembly: CommandClass(typeof(PointElimination))]
[assembly: CommandClass(typeof(SubDMeshHandler))]
[assembly: CommandClass(typeof(Class1))]
[assembly: CommandClass(typeof(CMD_PABoundingBox))]
[assembly: CommandClass(typeof(CMD_Help))]
[assembly: CommandClass(typeof(TerrainComputeC.My.ModifyCmd))]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.None)]
[assembly: AssemblyCompany("niaoge")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCopyright("Copyright © niaoge")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyDescription("")]
[assembly: AssemblyFileVersion("0.0.0.1")]
[assembly: AssemblyKeyName("")]
[assembly: AssemblyProduct("TerrainCompute")]
[assembly: AssemblyTitle("TerrainCompute")]
[assembly: AssemblyTrademark("")]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: ComVisible(true)]
[assembly: Guid("876BF797-B09F-4C4B-8373-486D17EC6E8A")]
